# =============================================================================
# Workflow: Semantic Knowledge Search
# Category: search
#
# The "Semantic Knowledge Search" workflow allows users to perform semantic
# searches for knowledge based on a natural language query, with optional
# filters for namespace and knowledge type. It takes inputs such as the query
# text, namespace root, namespace scope, and knowledge type, and constructs
# filters accordingly. The workflow then executes a search against a
# specified knowledge base index, returning relevant results based on the
# provided criteria. The process is triggered manually and includes steps for
# preparing and parsing filters before executing the search.
#
# Author: Elastic
# Created: 2025-11-13
# =============================================================================
name: Semantic Knowledge Search
description: Search for similar knowledge using semantic search with optional namespace and type filters


# ---------------------------------------------------------------------------
# INPUTS
# ---------------------------------------------------------------------------
# Runtime parameters provided when the workflow is triggered. Each input
# can specify:
#   - name: Unique identifier for the input
#   - type: Data type (string, number, boolean, array, object)
#   - required: Whether the input must be provided (default: false)
#   - default: Default value if not provided
# Reference inputs in steps using {{ inputs.input_name }} syntax
# ---------------------------------------------------------------------------
inputs:
  - name: query_text
    type: string
    description: Description of the knowledge you're looking for in natural semantic language.
    required: true
  - name: namespace_root
    type: string
    description: |
      Optional root namespace filter:
      - "integration" for integration-specific knowledge
      - "kibana" for Kibana patterns
      - "elasticsearch" for Elasticsearch patterns
    required: false
  - name: namespace_scope
    type: string
    description: |
      Optional scope filter:
      - When root="integration": integration name (e.g., "1password", "kubernetes")
      - When root="kibana": product area (e.g., "visualizations", "dashboards")
      - When root="elasticsearch": product area (e.g., "pipelines")
    required: false
  - name: knowledge_type
    type: string
    description: Optional filter (e.g., 'security_use_case', 'field_group', 'detection_pattern')
    required: false


# ---------------------------------------------------------------------------
# CONSTANTS
# ---------------------------------------------------------------------------
# Reusable configuration values defined once and referenced throughout the
# workflow using {{ consts.key_name }} syntax. Use constants for:
#   - API endpoints and URLs
#   - API keys and authentication tokens (use secrets in production)
#   - Environment-specific configuration
#   - Values that may need to change across environments
# ---------------------------------------------------------------------------
consts:
  index_name: "knowledge_base"


# ---------------------------------------------------------------------------
# TRIGGERS
# ---------------------------------------------------------------------------
# Defines how and when this workflow is executed. Supported trigger types:
#   - manual: Run on-demand from the Kibana UI or API
#   - scheduled: Run on a recurring schedule (every: "5m" or rrule)
#   - alert: Run automatically when a security alert is triggered
# ---------------------------------------------------------------------------
triggers:
  - type: manual


# ---------------------------------------------------------------------------
# STEPS
# ---------------------------------------------------------------------------
# The sequence of actions this workflow performs. Each step executes an
# action and can reference outputs from previous steps. Key properties:
#   - name: Unique identifier for referencing this step's output
#   - type: The action to perform (http, elasticsearch.search, foreach, etc.)
#   - with: Parameters passed to the action
#   - condition: Optional expression to conditionally run the step
#   - on-failure: Error handling configuration (retry, continue, etc.)
# Access step outputs using {{ steps.step_name.output.field }} syntax
# ---------------------------------------------------------------------------
steps:

  # -------------------------------------------------------------------------
  # STEP 1: prepare_filters
  # -------------------------------------------------------------------------
  # Outputs a message to the workflow execution log for visibility.
  # Liquid syntax used:
  # - `join` - Joins array elements into string
  # - `split` - Splits string into array
  # - `append` - Adds string to end
  # - `{% if %}` - Conditional logic based on expression
  # - `{% assign %}` - Creates/assigns a variable
  # -------------------------------------------------------------------------
  - name: prepare_filters
    type: console
    with:
      message: |
        {% assign filters = "" | split: "" %}
        {% if inputs.knowledge_type %}
          {% assign filter_obj = '{"term": {"knowledge_type": "' | append: inputs.knowledge_type | append: '"}}' %}
          {% assign filters = filters | push: filter_obj %}
        {% endif %}
        {% if inputs.namespace_root %}
          {% assign filter_obj = '{"term": {"namespace.root": "' | append: inputs.namespace_root | append: '"}}' %}
          {% assign filters = filters | push: filter_obj %}
        {% endif %}
        {% if inputs.namespace_scope %}
          {% assign filter_obj = '{"term": {"namespace.scope": "' | append: inputs.namespace_scope | append: '"}}' %}
          {% assign filters = filters | push: filter_obj %}
        {% endif %}
        [{{ filters | join: "," }}]


  # -------------------------------------------------------------------------
  # STEP 2: parse_filters
  # -------------------------------------------------------------------------
  # Outputs a message to the workflow execution log for visibility.
  # Liquid syntax used:
  # - `json_parse` - Parses JSON string to object
  # - References output from previous step(s)
  # -------------------------------------------------------------------------
  - name: parse_filters
    type: console
    with:
      message: ${{ steps.prepare_filters.output | json_parse }}


  # -------------------------------------------------------------------------
  # STEP 3: search_knowledge
  # -------------------------------------------------------------------------
  # Executes a search query against one or more Elasticsearch indices.
  # Uses the Query DSL to define match criteria for documents.
  # Output: {{ steps.search_knowledge.output.hits }} contains matching
  # documents.
  # Liquid syntax used:
  # - References output from previous step(s)
  # - References workflow input parameter(s)
  # - References workflow constant(s)
  # -------------------------------------------------------------------------
  - name: search_knowledge
    type: elasticsearch.search
    with:
      index: "{{ consts.index_name }}"
      size: 5
      query:
        bool:
          should:
            - semantic:
                field: semantic_summary
                query: "{{ inputs.query_text }}"
          must: ${{ steps.parse_filters.output }}
          minimum_should_match: 1