# =============================================================================
# Workflow: Semantic Knowledge Search
# Category: search
#
# Performs semantic searches against knowledge base indices using the
# semantic_summary field. Supports optional namespace and type filters.
#
# Uses explicit HTTP auth for reliability when called through the
# subagent chain (Agent Builder converse API loses ES session context).
#
# Author: Elastic (modified by Security Agent Mesh)
# Created: 2025-11-13
# =============================================================================
name: Semantic Knowledge Search
description: Search for similar knowledge using semantic search with optional namespace and type filters

inputs:
  - name: index_name
    type: string
    description: "Knowledge base index to search (e.g., kb-soc-ops, kb-detection-rules, kb-compliance, kb-threat-intel)"
    required: true
  - name: query_text
    type: string
    description: Description of the knowledge you're looking for in natural semantic language.
    required: true
  - name: namespace_root
    type: string
    description: |
      Optional root namespace filter:
      - "integration" for integration-specific knowledge
      - "kibana" for Kibana patterns
      - "elasticsearch" for Elasticsearch patterns
    required: false
  - name: namespace_scope
    type: string
    description: |
      Optional scope filter:
      - When root="integration": integration name (e.g., "1password", "kubernetes")
      - When root="kibana": product area (e.g., "visualizations", "dashboards")
      - When root="elasticsearch": product area (e.g., "pipelines")
    required: false
  - name: knowledge_type
    type: string
    description: Optional filter (e.g., 'security_use_case', 'field_group', 'detection_pattern')
    required: false

consts:
  es_url: "__ES_URL__"
  es_api_key: "__ES_API_KEY__"

triggers:
  - type: manual

steps:

  - name: prepare_filters
    type: console
    with:
      message: |
        {% assign filters = "" | split: "" %}
        {% if inputs.knowledge_type %}
          {% assign filter_obj = '{"term": {"knowledge_type": "' | append: inputs.knowledge_type | append: '"}}' %}
          {% assign filters = filters | push: filter_obj %}
        {% endif %}
        {% if inputs.namespace_root %}
          {% assign filter_obj = '{"term": {"namespace.root": "' | append: inputs.namespace_root | append: '"}}' %}
          {% assign filters = filters | push: filter_obj %}
        {% endif %}
        {% if inputs.namespace_scope %}
          {% assign filter_obj = '{"term": {"namespace.scope": "' | append: inputs.namespace_scope | append: '"}}' %}
          {% assign filters = filters | push: filter_obj %}
        {% endif %}
        [{{ filters | join: "," }}]

  - name: parse_filters
    type: console
    with:
      message: "{{ steps.prepare_filters.output | json_parse }}"

  - name: search_knowledge
    type: http
    with:
      method: POST
      url: "{{ consts.es_url }}/{{ inputs.index_name }}/_search"
      headers:
        Content-Type: application/json
        Authorization: "ApiKey {{ consts.es_api_key }}"
      body:
        size: 5
        query:
          bool:
            should:
              - semantic:
                  field: semantic_summary
                  query: "{{ inputs.query_text }}"
            must: "{{ steps.parse_filters.output }}"
            minimum_should_match: 1

  - name: output_results
    type: console
    with:
      message: "{{ steps.search_knowledge.output.data.hits }}"
