# =============================================================================
# Workflow: 🔎 Web Search
# Category: search
#
# The workflow named "Web Search" is manually triggered and allows users to
# input a search query, defaulting to "what is the population of Malta?". It
# performs a web search using the Brave Search API, sending a GET request
# with the encoded query and specific headers, including an authorization
# token. The workflow is currently enabled for use.
#
# Author: Elastic
# Created: 2025-11-07
# =============================================================================
name: 🔎 Web Search
enabled: true

# ---------------------------------------------------------------------------
# TRIGGERS
# ---------------------------------------------------------------------------
# Defines how and when this workflow is executed. Supported trigger types:
#   - manual: Run on-demand from the Kibana UI or API
#   - scheduled: Run on a recurring schedule (every: "5m" or rrule)
#   - alert: Run automatically when a security alert is triggered
# ---------------------------------------------------------------------------
triggers:
  - type: manual

# ---------------------------------------------------------------------------
# INPUTS
# ---------------------------------------------------------------------------
# Runtime parameters provided when the workflow is triggered. Each input
# can specify:
#   - name: Unique identifier for the input
#   - type: Data type (string, number, boolean, array, object)
#   - required: Whether the input must be provided (default: false)
#   - default: Default value if not provided
# Reference inputs in steps using {{ inputs.input_name }} syntax
# ---------------------------------------------------------------------------
inputs:
  - name: query
    default: what is the population of Malta?
    description: query to pass into google search
    type: string

# ---------------------------------------------------------------------------
# STEPS
# ---------------------------------------------------------------------------
# The sequence of actions this workflow performs. Each step executes an
# action and can reference outputs from previous steps. Key properties:
#   - name: Unique identifier for referencing this step's output
#   - type: The action to perform (http, elasticsearch.search, foreach, etc.)
#   - with: Parameters passed to the action
#   - condition: Optional expression to conditionally run the step
#   - on-failure: Error handling configuration (retry, continue, etc.)
# Access step outputs using {{ steps.step_name.output.field }} syntax
# ---------------------------------------------------------------------------
steps:

  # -------------------------------------------------------------------------
  # STEP 1: web_search
  # -------------------------------------------------------------------------
  # Performs a web search using the Brave Search API.
  # Liquid syntax used:
  # - `url_encode` - URL-encodes string
  # -------------------------------------------------------------------------
  - name: web_search
    type: http
    with:
      url: https://api.search.brave.com/res/v1/web/search inputs.query | url_encode}}
      method: GET
      headers:
        Accept: application/json
        Accept-Encoding: gzip
        X-Subscription-Token: secret
