# =============================================================================
# Workflow: Add Knowledge Document
# Category: knowledge
#
# Indexes a new document into any Elasticsearch index. Takes the index name
# and a JSON document body as inputs — makes no assumptions about the index
# mapping or field structure. The index must already exist.
#
# This is a generic building block. The calling agent or workflow is
# responsible for providing the correct field names for the target index.
#
# Author: Elastic
# Created: 2026-02-19
# =============================================================================
name: Add Knowledge Document
description: Index a new document into any Elasticsearch index.
enabled: true

tags:
  - data
  - knowledge

triggers:
  - type: manual

inputs:
  - name: index_name
    type: string
    description: Target Elasticsearch index name
    required: true
  - name: document
    type: string
    description: The document body to index (any valid JSON object)
    required: true

consts:
  es_url: "__ES_URL__"
  es_api_key: "__ES_API_KEY__"

steps:

  - name: index_document
    type: http
    with:
      method: POST
      url: "{{ consts.es_url }}/{{ inputs.index_name }}/_doc"
      headers:
        Content-Type: application/json
        Authorization: "ApiKey {{ consts.es_api_key }}"
      body: "{{ inputs.document }}"

  - name: confirm
    type: console
    with:
      message: "Document indexed in {{ inputs.index_name }} with ID: {{ steps.index_document.output.data._id }}"

