# =============================================================================
# Workflow: Add Knowledge Document
# Category: knowledge
#
# Indexes a new document into any Elasticsearch index. Takes the index name
# and a JSON document body as inputs — makes no assumptions about the index
# mapping or field structure. The index must already exist.
#
# This is a generic building block. The calling agent or workflow is
# responsible for providing the correct field names for the target index.
#
# Author: Elastic
# Created: 2026-02-19
# =============================================================================
name: Add Knowledge Document
description: Index a new document into any Elasticsearch index.
enabled: true

tags:
  - data
  - knowledge

triggers:
  - type: manual

inputs:
  - name: index_name
    type: string
    description: Target Elasticsearch index name
    required: true
  - name: document
    type: object
    description: The document body to index (any valid JSON object)
    required: true

steps:

  - name: index_document
    type: elasticsearch.index
    with:
      index: "{{ inputs.index_name }}"
      document: "{{ inputs.document }}"

  - name: confirm
    type: console
    with:
      message: "Document indexed in {{ inputs.index_name }} with ID: {{ steps.index_document.output._id }}"

outputs:
  document_id:
    value: "{{ steps.index_document.output._id }}"
  index:
    value: "{{ inputs.index_name }}"
