# =============================================================================
# Workflow: Update Knowledge Document
# Category: knowledge
#
# Updates an existing document in any Elasticsearch index by ID. Takes the
# index name, document ID, and a partial document body. Uses the ES Update
# API so only the provided fields are changed — existing fields are
# preserved.
#
# This is a generic building block with no opinions on index mapping.
#
# Author: Elastic
# Created: 2026-02-19
# =============================================================================
name: Update Knowledge Document
description: Update an existing document in any Elasticsearch index by ID (partial update).
enabled: true

tags:
  - agent-mesh
  - data
  - knowledge

triggers:
  - type: manual

inputs:
  - name: index_name
    type: string
    description: Elasticsearch index containing the document
    required: true
  - name: document_id
    type: string
    description: The document ID to update
    required: true
  - name: document
    type: string
    description: Partial document body — only the fields provided will be updated
    required: true

consts:
  es_url: "__ES_URL__"
  es_api_key: "__ES_API_KEY__"

steps:

  - name: update_document
    type: http
    with:
      method: POST
      url: "{{ consts.es_url }}/{{ inputs.index_name }}/_update/{{ inputs.document_id }}"
      headers:
        Content-Type: application/json
        Authorization: "ApiKey {{ consts.es_api_key }}"
      body:
        doc: "{{ inputs.document }}"

  - name: confirm
    type: console
    with:
      message: "Document {{ inputs.document_id }} updated in {{ inputs.index_name }} (result: {{ steps.update_document.output.data.result }})"

