name: Call Subagent Workflow
description: Invoke a specialist agent via the Agent Builder converse API.
enabled: true

triggers:
  - type: manual

inputs:
  - name: agent_id
    type: string
    description: The ID of the agent to invoke
    required: true
  - name: question
    type: string
    description: The question or prompt to send to the subagent
    required: true

steps:

  - name: debug_inputs
    type: console
    with:
      message: "Calling agent={{ inputs.agent_id }} connector=__LLM_CONNECTOR_ID__"

  - name: converse_with_agent
    type: kibana.request
    with:
      method: POST
      path: /api/agent_builder/converse
      body:
        agent_id: "{{ inputs.agent_id }}"
        connector_id: "__LLM_CONNECTOR_ID__"
        input: "{{ inputs.question }}"
    timeout: 600s

  - name: filter_output
    type: console
    with:
      message: "{{ steps.converse_with_agent.output.data.response.message }}"
