# =============================================================================
# Workflow: Call Subagent Workflow
# Category: ai-agents
#
# The "Call Subagent Workflow" is a manual workflow designed to interact with
# a subagent using the Agent Builder. It requires two inputs: the agent ID
# and a question or prompt. The workflow consists of two main steps:
# conversing with the specified agent and filtering the output to display the
# response message.
#
# Author: Elastic
# Created: 2025-11-13
# =============================================================================
name: Call Subagent Workflow
description: Call a subagent workflow to converse with the Agent Builer agent.
enabled: true

# ---------------------------------------------------------------------------
# TRIGGERS
# ---------------------------------------------------------------------------
# Defines how and when this workflow is executed. Supported trigger types:
#   - manual: Run on-demand from the Kibana UI or API
#   - scheduled: Run on a recurring schedule (every: "5m" or rrule)
#   - alert: Run automatically when a security alert is triggered
# ---------------------------------------------------------------------------
triggers:
  - type: manual

# ---------------------------------------------------------------------------
# INPUTS
# ---------------------------------------------------------------------------
# Runtime parameters provided when the workflow is triggered. Each input
# can specify:
#   - name: Unique identifier for the input
#   - type: Data type (string, number, boolean, array, object)
#   - required: Whether the input must be provided (default: false)
#   - default: Default value if not provided
# Reference inputs in steps using {{ inputs.input_name }} syntax
# ---------------------------------------------------------------------------
inputs:
  - name: agent_id
    type: string
    description: The ID of the agent to invoke
    required: true
  - name: question
    type: string
    description: The question or prompt to send to the subagent
    required: true

# ---------------------------------------------------------------------------
# STEPS
# ---------------------------------------------------------------------------
# The sequence of actions this workflow performs. Each step executes an
# action and can reference outputs from previous steps. Key properties:
#   - name: Unique identifier for referencing this step's output
#   - type: The action to perform (http, elasticsearch.search, foreach, etc.)
#   - with: Parameters passed to the action
#   - condition: Optional expression to conditionally run the step
#   - on-failure: Error handling configuration (retry, continue, etc.)
# Access step outputs using {{ steps.step_name.output.field }} syntax
# ---------------------------------------------------------------------------
steps:

  # -------------------------------------------------------------------------
  # STEP 1: converse_with_agent
  # -------------------------------------------------------------------------
  # Invokes an AI agent via the Kibana Agent Builder API (POST
  # /api/agent/chat).
  # The agent uses configured tools and knowledge to analyze input and
  # respond.
  # Required: agentId, conversationId (or create new), input message.
  # Output: {{ steps.converse_with_agent.output.message }} contains the agent
  # response.
  # Liquid syntax used:
  # - References workflow input parameter(s)
  # -------------------------------------------------------------------------
  - name: converse_with_agent
    type: kibana.post_agent_builder_converse
    with:
      agent_id: "{{ inputs.agent_id }}"
      input: "{{ inputs.question }}"

  # -------------------------------------------------------------------------
  # STEP 2: filter_output
  # -------------------------------------------------------------------------
  # Outputs a message to the workflow execution log for visibility.
  # Liquid syntax used:
  # - References output from previous step(s)
  # -------------------------------------------------------------------------
  - name: filter_output
    type: console
    with:
      message: "{{ steps.converse_with_agent.output.response.message }}"