name: Invoke an Agent
description: Invoke an agent for alert triage via the Agent Builder converse API.
enabled: true

triggers:
  - type: manual
  - type: alert

consts:
  connector_id: "__LLM_CONNECTOR_ID__"

steps:

  - name: log_for_debug
    type: console
    with:
      message: "Alert event received, invoking triage agent with connector={{ consts.connector_id }}"

  - name: kibana_post_agent_builder_converse_step
    type: kibana.request
    with:
      method: POST
      path: /api/agent_builder/converse
      body:
        agent_id: alert.triage
        connector_id: "{{ consts.connector_id }}"
        input: "Triage the following alert based on your system instructions: {{event | json}}"
    timeout: 600s
