# =============================================================================
# Workflow: Get Investigation
# Category: investigation
#
# Retrieves the current state of an investigation context by document ID.
# Returns all evidence, actions taken, and pending actions.
#
# Author: Security Agent Mesh
# =============================================================================
name: Get Investigation
description: Retrieve the current state of an investigation context.
enabled: true

tags:
  - agent-mesh
  - investigation

triggers:
  - type: manual

inputs:
  - name: document_id
    type: string
    description: "Elasticsearch document ID of the investigation context"
    required: true

consts:
  es_url: "__ES_URL__"
  es_api_key: "__ES_API_KEY__"
  index_name: "investigation-contexts"

steps:

  - name: get_context
    type: http
    with:
      method: GET
      url: "{{ consts.es_url }}/{{ consts.index_name }}/_doc/{{ inputs.document_id }}"
      headers:
        Content-Type: application/json
        Authorization: "ApiKey {{ consts.es_api_key }}"

  - name: output_context
    type: console
    with:
      message: |
        Investigation: {{ steps.get_context.output.data._source.title }}
        Status: {{ steps.get_context.output.data._source.status }}
        Risk Tier: {{ steps.get_context.output.data._source.risk_tier }}
        Assigned Agent: {{ steps.get_context.output.data._source.assigned_agent }}
        Evidence Count: {{ steps.get_context.output.data._source.evidence | size }}
        Actions Taken: {{ steps.get_context.output.data._source.actions_taken | size }}
        Pending Actions: {{ steps.get_context.output.data._source.pending_actions | size }}

outputs:
  investigation:
    value: "{{ steps.get_context.output.data._source }}"
  document_id:
    value: "{{ steps.get_context.output.data._id }}"
