# =============================================================================
# Workflow: Search Agent Registry
# Category: ai-agents
#
# Searches the agent-registry index to find the best specialist agent for a
# given request. Uses semantic search on the agent description to match
# natural language queries to agent capabilities. Returns the agent_id,
# name, domain, and capabilities of the top match.
#
# Used by the orchestrator agent (or any agent) to discover which specialist
# to route a request to at runtime.
#
# Author: Security Agent Mesh
# Created: 2026-02-19
# =============================================================================
name: Search Agent Registry
description: Find the best specialist agent for a given request by searching the agent registry semantically.
enabled: true

tags:
  - agent-mesh
  - routing
  - infrastructure

triggers:
  - type: manual

inputs:
  - name: query
    type: string
    description: Natural language description of what the user needs help with
    required: true
  - name: domain_filter
    type: string
    description: Optional domain keyword to filter results (e.g., "detection_engineering", "compliance", "threat_intel")
    required: false

consts:
  registry_index: "agent-registry"

steps:

  - name: search_registry
    type: elasticsearch.search
    with:
      index: "{{ consts.registry_index }}"
      size: 3
      query:
        bool:
          must:
            - term:
                status: "active"
          should:
            - semantic:
                field: semantic_description
                query: "{{ inputs.query }}"
          minimum_should_match: 1

  - name: output_result
    type: console
    with:
      message: |
        {% if steps.search_registry.output.hits.total.value > 0 %}
        Best match: {{ steps.search_registry.output.hits.hits[0]._source.agent_name }} ({{ steps.search_registry.output.hits.hits[0]._source.domain }})
        Agent ID: {{ steps.search_registry.output.hits.hits[0]._source.agent_id }}
        Capabilities: {{ steps.search_registry.output.hits.hits[0]._source.capabilities | join: ", " }}
        Description: {{ steps.search_registry.output.hits.hits[0]._source.description }}
        {% else %}
        No matching agent found for this request.
        {% endif %}

