# =============================================================================
# Workflow: Search Agent Registry
# Category: ai-agents
#
# Searches the agent-registry index to find the best specialist agent for a
# given request. Uses semantic search on the agent description to match
# natural language queries to agent capabilities. Returns the agent_id,
# name, domain, and capabilities of the top match.
#
# Used by the orchestrator agent (or any agent) to discover which specialist
# to route a request to at runtime.
#
# Author: Security Agent Mesh
# Created: 2026-02-19
# =============================================================================
name: Search Agent Registry
description: Find the best specialist agent for a given request by searching the agent registry semantically.
enabled: true

tags:
  - agent-mesh
  - routing
  - infrastructure

triggers:
  - type: manual

inputs:
  - name: query
    type: string
    description: Natural language description of what the user needs help with
    required: true
  - name: domain_filter
    type: string
    description: Optional domain keyword to filter results (e.g., "detection_engineering", "compliance", "threat_intel")
    required: false

consts:
  registry_index: "agent-registry"

steps:

  - name: build_query_filters
    type: console
    with:
      message: |
        {% assign filters = "" | split: "" %}
        {% assign filter_obj = '{"term": {"status": "active"}}' %}
        {% assign filters = filters | push: filter_obj %}
        {% if inputs.domain_filter %}
          {% assign domain_filter = '{"term": {"domain": "' | append: inputs.domain_filter | append: '"}}' %}
          {% assign filters = filters | push: domain_filter %}
        {% endif %}
        [{{ filters | join: "," }}]

  - name: parse_filters
    type: console
    with:
      message: {{ steps.build_query_filters.output | json_parse }}

  - name: search_registry
    type: elasticsearch.search
    with:
      index: "{{ consts.registry_index }}"
      size: 3
      query:
        bool:
          should:
            - semantic:
                field: semantic_description
                query: "{{ inputs.query }}"
          must: "{{ steps.parse_filters.output }}"
          minimum_should_match: 1

  - name: output_result
    type: console
    with:
      message: |
        {% assign hits = steps.search_registry.output.hits.hits %}
        {% if hits.size > 0 %}
        Best match: {{ hits[0]._source.agent_name }} ({{ hits[0]._source.domain }})
        Agent ID: {{ hits[0]._source.agent_id }}
        Capabilities: {{ hits[0]._source.capabilities | join: ", " }}
        Description: {{ hits[0]._source.description }}
        {% else %}
        No matching agent found for this request.
        {% endif %}

