# =============================================================================
# Workflow: List Splunk Indices
# Category: integrations/splunk
#
# This workflow YAML defines a manual trigger for listing Splunk indices. It
# connects to a specified Splunk URL using HTTP POST to initiate a search for
# indices, waits for 5 seconds, and then retrieves the search results using a
# GET request. The workflow includes SSL verification skipping and uses
# authorization for secure access.
#
# Author: Elastic
# Created: 2025-12-19
# =============================================================================
version: '1'
name: List Splunk Indices
enabled: true

# ---------------------------------------------------------------------------
# TRIGGERS
# ---------------------------------------------------------------------------
# Defines how and when this workflow is executed. Supported trigger types:
#   - manual: Run on-demand from the Kibana UI or API
#   - scheduled: Run on a recurring schedule (every: "5m" or rrule)
#   - alert: Run automatically when a security alert is triggered
# ---------------------------------------------------------------------------
triggers:
  - type: manual

# ---------------------------------------------------------------------------
# CONSTANTS
# ---------------------------------------------------------------------------
# Reusable configuration values defined once and referenced throughout the
# workflow using {{ consts.key_name }} syntax. Use constants for:
#   - API endpoints and URLs
#   - API keys and authentication tokens (use secrets in production)
#   - Environment-specific configuration
#   - Values that may need to change across environments
# ---------------------------------------------------------------------------
consts:
  splunk_url: https://nlp.swiftcrypto.com:8089
  splunk_auth: secret

# ---------------------------------------------------------------------------
# STEPS
# ---------------------------------------------------------------------------
# The sequence of actions this workflow performs. Each step executes an
# action and can reference outputs from previous steps. Key properties:
#   - name: Unique identifier for referencing this step's output
#   - type: The action to perform (http, elasticsearch.search, foreach, etc.)
#   - with: Parameters passed to the action
#   - condition: Optional expression to conditionally run the step
#   - on-failure: Error handling configuration (retry, continue, etc.)
# Access step outputs using {{ steps.step_name.output.field }} syntax
# ---------------------------------------------------------------------------
steps:

  # -------------------------------------------------------------------------
  # STEP 1: list_splunk_indices
  # -------------------------------------------------------------------------
  # Submits a search query to Splunk and creates a search job.
  # The search job ID can be used to retrieve results after processing.
  # Liquid syntax used:
  # - References workflow constant(s)
  # -------------------------------------------------------------------------
  - name: list_splunk_indices
    type: http
    with:
      url: '{{consts.splunk_url}}/services/search/jobs'
      method: POST
      headers:
        Content-Type: application/x-www-form-urlencoded
        Authorization: '{{consts.splunk_auth}}'
      body: >-
        search=%7Crest%20%2Fservices%2Fdata%2Findexes%20count%3D0%20datatype%3Dall%20%7C%20search%20totalEventCount%20%3E%200%20title%20!%3D%20_*%20%7C%20table%20title%20totalEventCount&count=0&output_mode=json
      timeout: 30s
      fetcher:
        skip_ssl_verification: true

  # -------------------------------------------------------------------------
  # STEP 2: wait_for_search
  # -------------------------------------------------------------------------
  # Pauses workflow execution for a specified duration.
  # Useful for waiting on async operations or rate-limiting API calls.
  # -------------------------------------------------------------------------
  - name: wait_for_search
    type: wait
    with:
      duration: 5s

  # -------------------------------------------------------------------------
  # STEP 3: get_splunk_results
  # -------------------------------------------------------------------------
  # Submits a search query to Splunk and creates a search job.
  # The search job ID can be used to retrieve results after processing.
  # Liquid syntax used:
  # - References output from previous step(s)
  # - References workflow constant(s)
  # -------------------------------------------------------------------------
  - name: get_splunk_results
    type: http
    with:
      url: >-
        {{consts.splunk_url}}/services/search/jobs/{{steps.list_splunk_indices.output.data.sid}}/results?output_mode=json&count=0
      method: GET
      headers:
        Authorization: '{{consts.splunk_auth}}'
      timeout: 30s
      fetcher:
        skip_ssl_verification: true
