# =============================================================================
# Workflow: Splunk Query
# Category: integrations/splunk
#
# This workflow YAML defines a manual trigger for querying a Splunk instance
# using a specified search term. It sends a POST request to the Splunk API
# with the search term and retrieves the top 10 results in JSON format. The
# results are then output to the console for review.
#
# Author: Elastic
# Created: 2025-12-19
# =============================================================================
version: '1'

name: Splunk Query

description: Query Splunk and output results


# ---------------------------------------------------------------------------
# TRIGGERS
# ---------------------------------------------------------------------------
# Defines how and when this workflow is executed. Supported trigger types:
#   - manual: Run on-demand from the Kibana UI or API
#   - scheduled: Run on a recurring schedule (every: "5m" or rrule)
#   - alert: Run automatically when a security alert is triggered
# ---------------------------------------------------------------------------
triggers:
- type: manual


# ---------------------------------------------------------------------------
# CONSTANTS
# ---------------------------------------------------------------------------
# Reusable configuration values defined once and referenced throughout the
# workflow using {{ consts.key_name }} syntax. Use constants for:
#   - API endpoints and URLs
#   - API keys and authentication tokens (use secrets in production)
#   - Environment-specific configuration
#   - Values that may need to change across environments
# ---------------------------------------------------------------------------
consts:
  splunk_url: https://your-splunk-instance/services/search/jobs
  splunk_auth_token: base64-encoded-credentials


# ---------------------------------------------------------------------------
# INPUTS
# ---------------------------------------------------------------------------
# Runtime parameters provided when the workflow is triggered. Each input
# can specify:
#   - name: Unique identifier for the input
#   - type: Data type (string, number, boolean, array, object)
#   - required: Whether the input must be provided (default: false)
#   - default: Default value if not provided
# Reference inputs in steps using {{ inputs.input_name }} syntax
# ---------------------------------------------------------------------------
inputs:
- name: search_term
  type: string
  description: The term to search for in Splunk
  required: true


# ---------------------------------------------------------------------------
# STEPS
# ---------------------------------------------------------------------------
# The sequence of actions this workflow performs. Each step executes an
# action and can reference outputs from previous steps. Key properties:
#   - name: Unique identifier for referencing this step's output
#   - type: The action to perform (http, elasticsearch.search, foreach, etc.)
#   - with: Parameters passed to the action
#   - condition: Optional expression to conditionally run the step
#   - on-failure: Error handling configuration (retry, continue, etc.)
# Access step outputs using {{ steps.step_name.output.field }} syntax
# ---------------------------------------------------------------------------
steps:

# -------------------------------------------------------------------------
# STEP 1: query_splunk
# -------------------------------------------------------------------------
# Executes a query against Splunk to retrieve security or log data.
# Liquid syntax used:
# - References workflow input parameter(s)
# - References workflow constant(s)
# -------------------------------------------------------------------------
- name: query_splunk
  type: http
  with:
    url: '{{ consts.splunk_url }}'
    method: POST
    headers:
      Authorization: Basic {{ consts.splunk_auth_token }}
      Content-Type: application/x-www-form-urlencoded
    body: search=search index=main {{ inputs.search_term }} | head 10&output_mode=json&exec_mode=oneshot
    timeout: 60s


# -------------------------------------------------------------------------
# STEP 2: output_results
# -------------------------------------------------------------------------
# Formats and displays the results in a human-readable report format.
# This output is visible in the workflow execution logs.
# Liquid syntax used:
# - `json` - Converts object to JSON string
# - References output from previous step(s)
# -------------------------------------------------------------------------
- name: output_results
  type: console
  with:
    message: '{{ steps.query_splunk.output.data.results | json }}'