# =============================================================================
# Workflow: Execute
# Category: utilities
#
# Executes a shell command on an endpoint via Elastic Defend response
# actions. Uses explicit HTTP auth for subagent chain reliability.
#
# Author: Security Agent Mesh (based on Elastic template)
# =============================================================================
name: Execute
description: Execute a command on an endpoint via Elastic Defend response actions.
enabled: true

tags:
  - agent-mesh
  - utilities
  - response-actions

triggers:
  - type: manual

inputs:
  - name: endpointids
    default: []
    type: array
    description: "Endpoint IDs to execute the command on"
  - name: comment
    default: "Command executed via security mesh"
    type: string
    description: "Reason for executing this command"
  - name: command
    type: string
    description: "The command to execute on the endpoint"
    required: true

steps:

  - name: execute_action
    type: http
    with:
      method: POST
      url: "__KIBANA_URL__/s/__KIBANA_SPACE__/api/endpoint/action/execute"
      headers:
        Content-Type: application/json
        Authorization: "ApiKey __KIBANA_API_KEY__"
        kbn-xsrf: "true"
      body:
        endpoint_ids: "{{ inputs.endpointids }}"
        comment: "{{ inputs.comment }}"
        parameters:
          command: "{{ inputs.command }}"
          timeout: 600

  - name: confirm
    type: console
    with:
      message: "Execute action submitted. Action ID: {{ steps.execute_action.output.data.data.id }}"
