# =============================================================================
# Workflow: 🔲 Execute and Retrieve
# Category: utilities
#
# The workflow YAML defines a manual trigger for executing a command on
# specified endpoints and retrieving the action status. It takes inputs for
# endpoint IDs, a comment, and a command to execute, defaulting to a curl
# command. The workflow consists of three main steps: executing the action
# via a POST request, waiting for 30 seconds, and then retrieving the action
# status using a GET request. The workflow is tagged for easy identification
# and is enabled for use.
#
# Author: Elastic
# Created: 2025-12-04
# =============================================================================
version: '1'
name: 🔲 Execute and Retrieve
enabled: true

# ---------------------------------------------------------------------------
# TRIGGERS
# ---------------------------------------------------------------------------
# Defines how and when this workflow is executed. Supported trigger types:
#   - manual: Run on-demand from the Kibana UI or API
#   - scheduled: Run on a recurring schedule (every: "5m" or rrule)
#   - alert: Run automatically when a security alert is triggered
# ---------------------------------------------------------------------------
triggers:
  - type: manual

# ---------------------------------------------------------------------------
# TAGS
# ---------------------------------------------------------------------------
# Categories and labels for organizing, filtering, and discovering workflows
# in the Kibana UI. Tags help with:
#   - Categorizing workflows by use case (security, observability, etc.)
#   - Filtering in the workflow library
#   - Grouping related workflows together
# ---------------------------------------------------------------------------
tags: []
inputs:
  - name: endpointids
    default:
      - 7189af0c-161c-4b1b-8153-70fdf0cd7eb5
    type: array
  - name: comment
    default: This command is being run to emulate behavior
    type: string
  - name: command
    default: curl.exe icanhazip.com
    type: string

# ---------------------------------------------------------------------------
# STEPS
# ---------------------------------------------------------------------------
# The sequence of actions this workflow performs. Each step executes an
# action and can reference outputs from previous steps. Key properties:
#   - name: Unique identifier for referencing this step's output
#   - type: The action to perform (http, elasticsearch.search, foreach, etc.)
#   - with: Parameters passed to the action
#   - condition: Optional expression to conditionally run the step
#   - on-failure: Error handling configuration (retry, continue, etc.)
# Access step outputs using {{ steps.step_name.output.field }} syntax
# ---------------------------------------------------------------------------
steps:

  # -------------------------------------------------------------------------
  # STEP 1: execute_action
  # -------------------------------------------------------------------------
  # Executes a shell command on an endpoint via Elastic Defend response
  # actions.
  # Required: endpoint_ids, parameters.command. Optional: timeout (default
  # 600s).
  # Caution: Commands run with elevated privileges on the target endpoint.
  # Liquid syntax used:
  # - References workflow input parameter(s)
  # -------------------------------------------------------------------------
  - name: execute_action
    type: kibana.request
    with:
      method: POST
      path: /api/endpoint/action/execute
      body:
        endpoint_ids: ${{inputs.endpointids}}
        comment: '{{inputs.comment}}'
        parameters:
          command: '{{inputs.command}}'
          timeout: 600

  # -------------------------------------------------------------------------
  # STEP 2: wait
  # -------------------------------------------------------------------------
  # Pauses workflow execution for a specified duration.
  # Useful for waiting on async operations or rate-limiting API calls.
  # -------------------------------------------------------------------------
  - name: wait
    type: wait
    with:
      duration: 30s

  # -------------------------------------------------------------------------
  # STEP 3: get_action_status
  # -------------------------------------------------------------------------
  # Retrieves data from an external API endpoint via HTTP GET request.
  # -------------------------------------------------------------------------
  - name: get_action_status
    type: http
    with:
      method: GET
      url: >-
        https://your-deployment.elastic-cloud.com
      headers:
        Authorization: secret
        kbn-xsrf: kibana
