# =============================================================================
# Workflow: Invoke other workflows
# Category: utilities
#
# This YAML workflow is designed to manually invoke a set of predefined
# workflows using HTTP requests. It specifies a list of workflow IDs and
# constructs a POST request to trigger each workflow at a designated URL,
# including necessary headers for authentication and content type. The
# workflow is enabled and tagged for configuration changes and resetting
# defaults.
#
# Author: Elastic
# Created: 2025-11-20
# Tags: config change, reset defaults
# =============================================================================
name: Invoke other workflows
enabled: true

# ---------------------------------------------------------------------------
# TAGS
# ---------------------------------------------------------------------------
# Categories and labels for organizing, filtering, and discovering workflows
# in the Kibana UI. Tags help with:
#   - Categorizing workflows by use case (security, observability, etc.)
#   - Filtering in the workflow library
#   - Grouping related workflows together
# ---------------------------------------------------------------------------
tags: []
  - config change
  - reset defaults

# ---------------------------------------------------------------------------
# CONSTANTS
# ---------------------------------------------------------------------------
# Reusable configuration values defined once and referenced throughout the
# workflow using {{ consts.key_name }} syntax. Use constants for:
#   - API endpoints and URLs
#   - API keys and authentication tokens (use secrets in production)
#   - Environment-specific configuration
#   - Values that may need to change across environments
# ---------------------------------------------------------------------------
consts:
  api: redeacted
  url: https://es:9200/api/workflows
  workflows:
    - workflow-9a9b4d98-481b-4d59-a643-1071f4e0e78d
    - workflow-bf7bb199-4040-4d55-9f43-16ac42d1f38a

# ---------------------------------------------------------------------------
# TRIGGERS
# ---------------------------------------------------------------------------
# Defines how and when this workflow is executed. Supported trigger types:
#   - manual: Run on-demand from the Kibana UI or API
#   - scheduled: Run on a recurring schedule (every: "5m" or rrule)
#   - alert: Run automatically when a security alert is triggered
# ---------------------------------------------------------------------------
triggers:
  - type: manual

# ---------------------------------------------------------------------------
# STEPS
# ---------------------------------------------------------------------------
# The sequence of actions this workflow performs. Each step executes an
# action and can reference outputs from previous steps. Key properties:
#   - name: Unique identifier for referencing this step's output
#   - type: The action to perform (http, elasticsearch.search, foreach, etc.)
#   - with: Parameters passed to the action
#   - condition: Optional expression to conditionally run the step
#   - on-failure: Error handling configuration (retry, continue, etc.)
# Access step outputs using {{ steps.step_name.output.field }} syntax
# ---------------------------------------------------------------------------
steps:

 # -------------------------------------------------------------------------
 # STEP 1: run workflows
 # -------------------------------------------------------------------------
 # Iterates over a collection of items, executing the nested steps for each.
 # Access the current item via {{ item }} within the loop body.
 # Liquid syntax used:
 # - `json` - Converts object to JSON string
 # - References workflow constant(s)
 # -------------------------------------------------------------------------
 - name: run workflows
   type: foreach
   foreach: "{{consts.workflows | json}}"
   steps:

     # -------------------------------------------------------------------------
     # STEP 2: run workflow
     # -------------------------------------------------------------------------
     # Sends data to an external API endpoint via HTTP POST request.
     # Liquid syntax used:
     # - References workflow constant(s)
     # - References current item in foreach loop
     # -------------------------------------------------------------------------
     - name: run workflow
       type: http
       with:
        url: "{{consts.url}}/{{foreach.item}}/run"
        body:
          {"inputs":{}}
        method: POST
        headers: 
          Content-Type: application/json
          Authorization: ApiKey {{consts.api}}
          kbn-xsrf: workflow
          x-elastic-internal-origin: Kibana


