# =============================================================================
# Workflow: Release Host
# Category: utilities
#
# Releases a previously isolated endpoint, restoring network connectivity.
#
# Author: Security Agent Mesh
# =============================================================================
name: Release Host
description: Release a previously isolated endpoint, restoring network connectivity.
enabled: true

tags:
  - agent-mesh
  - utilities
  - response-actions
  - containment

triggers:
  - type: manual

inputs:
  - name: endpoint_id
    type: string
    description: "The endpoint ID to release from isolation"
    required: true
  - name: comment
    type: string
    description: "Justification for releasing this host"
    required: true

steps:

  - name: release
    type: http
    with:
      method: POST
      url: "__KIBANA_URL__/s/__KIBANA_SPACE__/api/endpoint/action/unisolate"
      headers:
        Content-Type: application/json
        Authorization: "ApiKey __KIBANA_API_KEY__"
        kbn-xsrf: "true"
      body:
        endpoint_ids:
          - "{{ inputs.endpoint_id }}"
        comment: "{{ inputs.comment }}"

  - name: confirm
    type: console
    with:
      message: |
        Host released from isolation.
        Endpoint: {{ inputs.endpoint_id }}
        Action ID: {{ steps.release.output.data.data.id }}
