# =============================================================================
# Workflow: URL Threat Scan
# Category: utilities
#
# The "URL Threat Scan" workflow utilizes the URLScan.io public API to scan a
# specified URL for threats and malicious content. It begins by submitting
# the URL for scanning, waits for the scan to complete, and then retrieves
# the results, including the scan status and any historical data. The
# workflow formats and displays a comprehensive report, indicating whether
# the URL is clean, suspicious, or malicious, along with relevant details
# such as the page title and IP address. It includes error handling with
# retry mechanisms for both the scan submission and result retrieval steps.
#
# Author: Elastic
# Created: 2025-11-13
# =============================================================================
name: URL Threat Scan
description: Scan URLs for threats and malicious content using URLScan.io public API.

# ---------------------------------------------------------------------------
# CONSTANTS
# ---------------------------------------------------------------------------
# Reusable configuration values defined once and referenced throughout the
# workflow using {{ consts.key_name }} syntax. Use constants for:
#   - API endpoints and URLs
#   - API keys and authentication tokens (use secrets in production)
#   - Environment-specific configuration
#   - Values that may need to change across environments
# ---------------------------------------------------------------------------
consts:
  history_query: datasource=scans&q=page.url # This can be configured depending on the history you want to retrieve
  urlscan_api_key: API_KEY
  urlscan_base_url: https://urlscan.io/api/v1

# ---------------------------------------------------------------------------
# INPUTS
# ---------------------------------------------------------------------------
# Runtime parameters provided when the workflow is triggered. Each input
# can specify:
#   - name: Unique identifier for the input
#   - type: Data type (string, number, boolean, array, object)
#   - required: Whether the input must be provided (default: false)
#   - default: Default value if not provided
# Reference inputs in steps using {{ inputs.input_name }} syntax
# ---------------------------------------------------------------------------
inputs:
  - name: target_url
    type: string
    description:
      The URL to scan for malicious content, phishing, or other threats
      (e.g., https://example.com)
    required: true

# ---------------------------------------------------------------------------
# TRIGGERS
# ---------------------------------------------------------------------------
# Defines how and when this workflow is executed. Supported trigger types:
#   - manual: Run on-demand from the Kibana UI or API
#   - scheduled: Run on a recurring schedule (every: "5m" or rrule)
#   - alert: Run automatically when a security alert is triggered
# ---------------------------------------------------------------------------
triggers:
  - type: manual

# ---------------------------------------------------------------------------
# STEPS
# ---------------------------------------------------------------------------
# The sequence of actions this workflow performs. Each step executes an
# action and can reference outputs from previous steps. Key properties:
#   - name: Unique identifier for referencing this step's output
#   - type: The action to perform (http, elasticsearch.search, foreach, etc.)
#   - with: Parameters passed to the action
#   - condition: Optional expression to conditionally run the step
#   - on-failure: Error handling configuration (retry, continue, etc.)
# Access step outputs using {{ steps.step_name.output.field }} syntax
# ---------------------------------------------------------------------------
steps:

  # -------------------------------------------------------------------------
  # STEP 1: submit_url_scan
  # -------------------------------------------------------------------------
  # Submits a URL to URLScan.io for security analysis and screenshot capture.
  # Returns scan results including malicious indicators and page metadata.
  # Includes retry logic to handle transient failures gracefully.
  # Liquid syntax used:
  # - References workflow input parameter(s)
  # - References workflow constant(s)
  # -------------------------------------------------------------------------
  - name: submit_url_scan
    type: http
    with:
      url: "{{ consts.urlscan_base_url }}/scan/"
      method: POST
      headers:
        api-key: "{{ consts.urlscan_api_key }}"
        Content-Type: application/json
      body:
        url: "{{ inputs.target_url }}"
        visibility: public
    on-failure:
      retry:
        max-attempts: 2
        delay: 3s
      continue: true

  # -------------------------------------------------------------------------
  # STEP 2: wait_for_scan
  # -------------------------------------------------------------------------
  # Pauses workflow execution for a specified duration.
  # Useful for waiting on async operations or rate-limiting API calls.
  # -------------------------------------------------------------------------
  - name: wait_for_scan
    type: wait
    with:
      duration: 30s

  # -------------------------------------------------------------------------
  # STEP 3: get_scan_results
  # -------------------------------------------------------------------------
  # Submits a URL to URLScan.io for security analysis and screenshot capture.
  # Returns scan results including malicious indicators and page metadata.
  # Includes retry logic to handle transient failures gracefully.
  # Liquid syntax used:
  # - References output from previous step(s)
  # - References workflow constant(s)
  # -------------------------------------------------------------------------
  - name: get_scan_results
    type: http
    with:
      url:
        "{{ consts.urlscan_base_url }}/result/{{ steps.submit_url_scan.output.data.uuid }}/"
      method: GET
    on-failure:
      retry:
        max-attempts: 3
        delay: 5s
      continue: true

  # -------------------------------------------------------------------------
  # STEP 4: search_existing_scans
  # -------------------------------------------------------------------------
  # Submits a URL to URLScan.io for security analysis and screenshot capture.
  # Returns scan results including malicious indicators and page metadata.
  # Includes retry logic to handle transient failures gracefully.
  # Liquid syntax used:
  # - References workflow input parameter(s)
  # - References workflow constant(s)
  # -------------------------------------------------------------------------
  - name: search_existing_scans
    type: http
    with:
      url:
        "{{ consts.urlscan_base_url }}/search?{{ consts.history_query }}:{{ inputs.target_url }}"
      method: GET
    on-failure:
      continue: true

  # -------------------------------------------------------------------------
  # STEP 5: format_results
  # -------------------------------------------------------------------------
  # Formats and displays the results in a human-readable report format.
  # This output is visible in the workflow execution logs.
  # Liquid syntax used:
  # - `{% if %}` - Conditional logic based on expression
  # - `{% elsif %}` - Additional condition branch
  # - References output from previous step(s)
  # - References workflow input parameter(s)
  # -------------------------------------------------------------------------
  - name: format_results
    type: console
    with:
      message: |
        === URL Threat Scan Report ===
        Target URL: {{ inputs.target_url }}

        Scan UUID: {{ steps.submit_url_scan.output.data.uuid }}

        Current Scan Results:

        - Scan Status: {{ steps.get_scan_results.output.data.verdicts.overall.score }}/100

        - Malicious: {{ steps.get_scan_results.output.data.verdicts.overall.malicious }}
        - Categories: {{ steps.get_scan_results.output.data.verdicts.overall.categories }}
        - Page Title: {{ steps.get_scan_results.output.data.page.title }}
        - IP Address: {{ steps.get_scan_results.output.data.page.ip }}
        - Server: {{ steps.get_scan_results.output.data.page.server }}
        - Country: {{ steps.get_scan_results.output.data.page.country }}

        Historical Data:
        - Total Previous Scans: {{ steps.search_existing_scans.output.data.total }}

        Threat Assessment:
        {% if steps.get_scan_results.output.data.verdicts.overall.malicious %}
        \U0001F6A8 MALICIOUS - This URL has been flagged as dangerous
        {% elsif steps.get_scan_results.output.data.verdicts.overall.score > 50 %}
        \u26A0\uFE0F SUSPICIOUS - This URL shows suspicious characteristics
        {% else %}
        \u2713 CLEAN - No immediate threats detected
        {% endif %}

        View Full Report:
        {{ steps.submit_url_scan.output.data.result }}