# =============================================================================
# Workflow: Aggregate Detection Feedback
# Category: feedback
#
# Scheduled workflow that queries security alerts for TP/FP tag ratios per
# detection rule over a configurable time window. Writes a summary document
# to kb-detection-rules so the Detection Engineering agent can review rule
# effectiveness and recommend tuning.
#
# This closes the detection quality feedback loop:
#   Rule fires -> Analyst tags TP/FP -> This workflow aggregates ->
#   Detection Engineer reviews -> Rule tuned
#
# Author: Security Agent Mesh
# =============================================================================
name: Aggregate Detection Feedback
description: Scheduled aggregation of TP/FP ratios per detection rule for quality feedback.
enabled: true

tags:
  - agent-mesh
  - feedback
  - detection-engineering

triggers:
  - type: scheduled
    with:
      every: "24h"

inputs:
  - name: lookback_days
    type: number
    description: "Number of days to look back for alert data"
    default: "30"

consts:
  alerts_index: ".alerts-security.alerts-default"
  kb_index: "kb-detection-rules"

steps:

  - name: query_tp_counts
    type: elasticsearch.search
    with:
      index: "{{ consts.alerts_index }}"
      size: 0
      query:
        bool:
          must:
            - range:
                "@timestamp":
                  gte: "now-{{ inputs.lookback_days }}d"
            - term:
                kibana.alert.workflow_tags: "true-positive"
      aggregations:
        by_rule:
          terms:
            field: "kibana.alert.rule.name"
            size: 500
    on-failure:
      continue: true

  - name: query_fp_counts
    type: elasticsearch.search
    with:
      index: "{{ consts.alerts_index }}"
      size: 0
      query:
        bool:
          must:
            - range:
                "@timestamp":
                  gte: "now-{{ inputs.lookback_days }}d"
            - term:
                kibana.alert.workflow_tags: "false-positive"
      aggregations:
        by_rule:
          terms:
            field: "kibana.alert.rule.name"
            size: 500
    on-failure:
      continue: true

  - name: query_total_counts
    type: elasticsearch.search
    with:
      index: "{{ consts.alerts_index }}"
      size: 0
      query:
        range:
          "@timestamp":
            gte: "now-{{ inputs.lookback_days }}d"
      aggregations:
        by_rule:
          terms:
            field: "kibana.alert.rule.name"
            size: 500

  - name: write_feedback_summary
    type: elasticsearch.index
    with:
      index: "{{ consts.kb_index }}"
      document:
        title: "Detection Feedback Summary — {{ 'now' | date: '%Y-%m-%d' }}"
        content: |
          Automated detection quality feedback aggregated over the last {{ inputs.lookback_days }} days.
          Total rules with alerts: {{ steps.query_total_counts.output.aggregations.by_rule.buckets | size }}
          Rules with TP tags: {{ steps.query_tp_counts.output.aggregations.by_rule.buckets | size }}
          Rules with FP tags: {{ steps.query_fp_counts.output.aggregations.by_rule.buckets | size }}
        semantic_summary: "Detection rule quality feedback showing true positive and false positive rates per rule for the last {{ inputs.lookback_days }} days"
        category: "feedback"
        source: "aggregate-detection-feedback"
        tags:
          - feedback
          - detection-quality
          - automated
        created_at: "{{ 'now' | date: '%Y-%m-%dT%H:%M:%SZ' }}"
        updated_at: "{{ 'now' | date: '%Y-%m-%dT%H:%M:%SZ' }}"
        expires_at: "{{ 'now' | date: '%Y-%m-%dT%H:%M:%SZ' | plus: 2592000 }}"
        metadata:
          lookback_days: "{{ inputs.lookback_days }}"
          tp_buckets: "{{ steps.query_tp_counts.output.aggregations.by_rule.buckets }}"
          fp_buckets: "{{ steps.query_fp_counts.output.aggregations.by_rule.buckets }}"
          total_buckets: "{{ steps.query_total_counts.output.aggregations.by_rule.buckets }}"

  - name: confirm
    type: console
    with:
      message: "Detection feedback summary written to {{ consts.kb_index }}"
