# =============================================================================
# Workflow: Add Alert Tag - FP
# Category: security/detection
#
# Tags a security alert as a false positive. Uses explicit HTTP auth to
# work reliably when invoked through the agent mesh subagent chain.
#
# Author: Security Agent Mesh
# =============================================================================
name: Add Alert Tag - FP
description: Tag a security alert as a false positive.
enabled: true

tags:
  - agent-mesh
  - detection
  - triage

triggers:
  - type: manual

inputs:
  - name: alertid
    type: string
    description: "The alert ID to tag as false positive"
    required: true

steps:

  - name: set_fp_tag
    type: http
    with:
      method: POST
      url: "__KIBANA_URL__/s/__KIBANA_SPACE__/api/detection_engine/signals/tags"
      headers:
        Content-Type: application/json
        Authorization: "ApiKey __KIBANA_API_KEY__"
        kbn-xsrf: "true"
      body:
        ids:
          - "{{ inputs.alertid }}"
        tags:
          tags_to_add:
            - "Triaged as False Positive by AI"
          tags_to_remove: []

  - name: confirm
    type: console
    with:
      message: "Alert {{ inputs.alertid }} tagged as False Positive"
