# =============================================================================
# Workflow: Check Field Availability
# Category: security/detection
#
# Verifies that specific ECS fields exist in the customer's log data by
# checking field capabilities against the specified index pattern. Used
# before creating detection rules to ensure the required data sources are
# present.
#
# Author: Security Agent Mesh
# =============================================================================
name: Check Field Availability
description: Verify that ECS fields exist in logs-* before creating detection rules.
enabled: true

tags:
  - agent-mesh
  - detection-engineering

triggers:
  - type: manual

inputs:
  - name: field_names
    type: string
    description: "Comma-separated list of field names to check (e.g., 'process.name,event.action,source.ip')"
    required: true
  - name: index_pattern
    type: string
    description: "Index pattern to check against"
    default: "logs-*"
  - name: time_range
    type: string
    description: "How far back to look for data"
    default: "7d"

consts:
  es_url: "__ES_URL__"
  es_api_key: "__ES_API_KEY__"

steps:

  - name: check_fields
    type: http
    with:
      method: POST
      url: "{{ consts.es_url }}/{{ inputs.index_pattern }}/_field_caps"
      headers:
        Content-Type: application/json
        Authorization: "ApiKey {{ consts.es_api_key }}"
      body:
        fields: "{{ inputs.field_names }}"

  - name: output_results
    type: console
    with:
      message: |
        Field availability check for index pattern: {{ inputs.index_pattern }}
        Fields requested: {{ inputs.field_names }}
        Results: {{ steps.check_fields.output.data.fields }}

outputs:
  fields:
    value: "{{ steps.check_fields.output.data.fields }}"
