# =============================================================================
# Workflow: Create Detection Rule
# Category: security/detection
#
# Creates a new detection rule via the Kibana Detection Engine API.
# Rules are created DISABLED by default (Tier 1 governance).
#
# IMPORTANT: Liquid templates render everything as strings. Fields that
# require non-string types (risk_score: number, tags: array) use static
# YAML values. risk_score is set via a create-then-patch pattern to match
# the severity input.
#
# Handles both ES|QL rules (no index field) and standard rules (KQL/EQL
# with index patterns).
#
# NOTE: All step names must be globally unique across the workflow, even
# inside if-branches.
#
# Author: Security Agent Mesh
# =============================================================================
name: Create Detection Rule
description: Create a new detection rule (disabled by default for governance review).
enabled: true

tags:
  - agent-mesh
  - detection-engineering

triggers:
  - type: manual

inputs:
  - name: name
    type: string
    description: "Rule name"
    required: true
  - name: description
    type: string
    description: "Rule description including detection logic and MITRE mapping"
    required: true
  - name: rule_type
    type: string
    description: "Rule type: esql, query, threshold, eql, new_terms"
    default: "esql"
  - name: query
    type: string
    description: "The detection query (ES|QL, KQL, or EQL depending on type)"
    required: true
  - name: language
    type: string
    description: "Query language: esql, kuery, or eql"
    default: "esql"
  - name: severity
    type: string
    description: "Rule severity: low, medium, high, critical"
    default: "medium"
  - name: interval
    type: string
    description: "Rule run interval"
    default: "5m"
  - name: from
    type: string
    description: "Lookback period"
    default: "now-6m"

steps:

  # --- Branch: ES|QL rules (no index field) ---
  - name: branch_esql
    type: if
    condition: inputs.rule_type: esql
    steps:
      - name: post_esql_rule
        type: http
        with:
          method: POST
          url: "__KIBANA_URL__/s/__KIBANA_SPACE__/api/detection_engine/rules"
          headers:
            Content-Type: application/json
            Authorization: "ApiKey __KIBANA_API_KEY__"
            kbn-xsrf: "true"
          body:
            name: "{{ inputs.name }}"
            description: "{{ inputs.description }}"
            type: "esql"
            query: "{{ inputs.query }}"
            language: "esql"
            severity: "{{ inputs.severity }}"
            risk_score: 47
            tags:
              - agent-mesh
              - auto-generated
            interval: "{{ inputs.interval }}"
            from: "{{ inputs.from }}"
            enabled: false

  # --- Branch: Standard rules (KQL/EQL/threshold — require index) ---
  - name: branch_standard
    type: if
    condition: NOT inputs.rule_type: esql
    steps:
      - name: post_standard_rule
        type: http
        with:
          method: POST
          url: "__KIBANA_URL__/s/__KIBANA_SPACE__/api/detection_engine/rules"
          headers:
            Content-Type: application/json
            Authorization: "ApiKey __KIBANA_API_KEY__"
            kbn-xsrf: "true"
          body:
            name: "{{ inputs.name }}"
            description: "{{ inputs.description }}"
            type: "{{ inputs.rule_type }}"
            query: "{{ inputs.query }}"
            language: "{{ inputs.language }}"
            index:
              - "logs-*"
            severity: "{{ inputs.severity }}"
            risk_score: 47
            tags:
              - agent-mesh
              - auto-generated
            interval: "{{ inputs.interval }}"
            from: "{{ inputs.from }}"
            enabled: false

  # --- Patch risk_score to match severity ---
  # Liquid renders numbers as strings, so we create with 47 (medium)
  # then patch to the correct value for other severities.

  - name: patch_risk_low
    type: if
    condition: inputs.severity: low
    steps:
      - name: patch_to_21
        type: http
        with:
          method: PATCH
          url: "__KIBANA_URL__/s/__KIBANA_SPACE__/api/detection_engine/rules"
          headers:
            Content-Type: application/json
            Authorization: "ApiKey __KIBANA_API_KEY__"
            kbn-xsrf: "true"
          body:
            id: "{{ steps.branch_esql.steps.post_esql_rule.output.data.id | default: steps.branch_standard.steps.post_standard_rule.output.data.id }}"
            risk_score: 21

  - name: patch_risk_high
    type: if
    condition: inputs.severity: high
    steps:
      - name: patch_to_73
        type: http
        with:
          method: PATCH
          url: "__KIBANA_URL__/s/__KIBANA_SPACE__/api/detection_engine/rules"
          headers:
            Content-Type: application/json
            Authorization: "ApiKey __KIBANA_API_KEY__"
            kbn-xsrf: "true"
          body:
            id: "{{ steps.branch_esql.steps.post_esql_rule.output.data.id | default: steps.branch_standard.steps.post_standard_rule.output.data.id }}"
            risk_score: 73

  - name: patch_risk_critical
    type: if
    condition: inputs.severity: critical
    steps:
      - name: patch_to_99
        type: http
        with:
          method: PATCH
          url: "__KIBANA_URL__/s/__KIBANA_SPACE__/api/detection_engine/rules"
          headers:
            Content-Type: application/json
            Authorization: "ApiKey __KIBANA_API_KEY__"
            kbn-xsrf: "true"
          body:
            id: "{{ steps.branch_esql.steps.post_esql_rule.output.data.id | default: steps.branch_standard.steps.post_standard_rule.output.data.id }}"
            risk_score: 99

  - name: confirm
    type: console
    with:
      message: |
        Rule created (DISABLED):
        Name: {{ steps.branch_esql.steps.post_esql_rule.output.data.name | default: steps.branch_standard.steps.post_standard_rule.output.data.name }}
        ID: {{ steps.branch_esql.steps.post_esql_rule.output.data.id | default: steps.branch_standard.steps.post_standard_rule.output.data.id }}
        Rule ID: {{ steps.branch_esql.steps.post_esql_rule.output.data.rule_id | default: steps.branch_standard.steps.post_standard_rule.output.data.rule_id }}
        Type: {{ steps.branch_esql.steps.post_esql_rule.output.data.type | default: steps.branch_standard.steps.post_standard_rule.output.data.type }}
        Severity: {{ steps.branch_esql.steps.post_esql_rule.output.data.severity | default: steps.branch_standard.steps.post_standard_rule.output.data.severity }}
        Note: Rule is disabled. Use Enable/Disable Rule to activate after governance review.
