# =============================================================================
# Workflow: Create Alert Note
# Category: security/detection
#
# Adds an investigation note to a security alert. Uses explicit HTTP auth
# for subagent chain reliability.
#
# Author: Security Agent Mesh
# =============================================================================
name: Create Alert Note
description: Add investigation notes to a security alert.
enabled: true

tags:
  - agent-mesh
  - detection
  - triage

triggers:
  - type: manual

inputs:
  - name: note
    type: string
    description: "The investigation note to add"
    required: true
  - name: alertid
    type: string
    description: "The alert ID to attach the note to"
    required: true

steps:

  - name: add_note
    type: http
    with:
      method: POST
      url: "__KIBANA_URL__/s/__KIBANA_SPACE__/api/note"
      headers:
        Content-Type: application/json
        Authorization: "ApiKey __KIBANA_API_KEY__"
        kbn-xsrf: "true"
        elastic-api-version: "2023-10-31"
      body:
        note:
          timelineId: ""
          eventId: "{{ inputs.alertid }}"
          note: "{{ inputs.note }}"

  - name: confirm
    type: console
    with:
      message: "Note added to alert {{ inputs.alertid }}"
