# =============================================================================
# Workflow: Enable/Disable Detection Rule
# Category: security/detection
#
# Toggles a detection rule's enabled status. Enabling is a Tier 2
# governance action — the agent should check governance policy first.
#
# Uses if-branches to set the enabled field as a native YAML boolean
# (Liquid renders everything as strings, and the API rejects string
# values for the enabled field).
#
# Accepts either rule_id (slug) or saved object id (UUID).
#
# Author: Security Agent Mesh
# =============================================================================
name: Enable Disable Rule
description: Toggle a detection rule on or off by rule_id.
enabled: true

tags:
  - agent-mesh
  - detection-engineering

triggers:
  - type: manual

inputs:
  - name: rule_id
    type: string
    description: "The rule_id (slug) or saved object id (UUID) of the detection rule"
    required: true
  - name: enabled
    type: string
    description: "Set to 'true' to enable, 'false' to disable"
    required: true

steps:

  # Look up the rule to get its saved object ID (needed for PATCH)
  - name: try_by_rule_id
    type: http
    with:
      method: GET
      url: "__KIBANA_URL__/s/__KIBANA_SPACE__/api/detection_engine/rules?rule_id={{ inputs.rule_id }}"
      headers:
        Authorization: "ApiKey __KIBANA_API_KEY__"
        kbn-xsrf: "true"
    on-failure:
      continue: true

  - name: try_by_uuid
    type: http
    condition: "{{ steps.try_by_rule_id.error != null }}"
    with:
      method: GET
      url: "__KIBANA_URL__/s/__KIBANA_SPACE__/api/detection_engine/rules?id={{ inputs.rule_id }}"
      headers:
        Authorization: "ApiKey __KIBANA_API_KEY__"
        kbn-xsrf: "true"
    on-failure:
      continue: true

  # Branch: enable
  - name: branch_enable
    type: if
    condition: 'inputs.enabled: "true"'
    steps:
      - name: enable_rule
        type: http
        with:
          method: PATCH
          url: "__KIBANA_URL__/s/__KIBANA_SPACE__/api/detection_engine/rules"
          headers:
            Content-Type: application/json
            Authorization: "ApiKey __KIBANA_API_KEY__"
            kbn-xsrf: "true"
          body:
            id: "{{ steps.try_by_uuid.output.data.id | default: steps.try_by_rule_id.output.data.id }}"
            enabled: true
        on-failure:
          continue: true

  # Branch: disable
  - name: branch_disable
    type: if
    condition: 'inputs.enabled: "false"'
    steps:
      - name: disable_rule
        type: http
        with:
          method: PATCH
          url: "__KIBANA_URL__/s/__KIBANA_SPACE__/api/detection_engine/rules"
          headers:
            Content-Type: application/json
            Authorization: "ApiKey __KIBANA_API_KEY__"
            kbn-xsrf: "true"
          body:
            id: "{{ steps.try_by_uuid.output.data.id | default: steps.try_by_rule_id.output.data.id }}"
            enabled: false
        on-failure:
          continue: true

  - name: confirm
    type: console
    with:
      message: |
        {% assign result = steps.branch_enable.steps.enable_rule.output.data | default: steps.branch_disable.steps.disable_rule.output.data %}
        Rule {{ inputs.rule_id }}: {% if inputs.enabled == "true" %}ENABLED{% else %}DISABLED{% endif %}
        Name: {{ result.name }}
        ID: {{ result.id }}
