# =============================================================================
# Workflow: Get Rule Details
# Category: security/detection
#
# Retrieves the full definition of a detection rule. Accepts either
# rule_id (slug) or Kibana saved object id (UUID) — tries rule_id first,
# falls back to id. Uses explicit HTTP auth for subagent chain reliability.
#
# Author: Security Agent Mesh
# =============================================================================
name: Get Rule Details
description: Get the full definition of a detection rule by ID.
enabled: true

tags:
  - agent-mesh
  - detection-engineering

triggers:
  - type: manual

inputs:
  - name: rule_id
    type: string
    description: "The detection rule_id (slug-style) or Kibana saved object id (UUID). Both formats accepted."
    required: true

steps:

  - name: try_by_rule_id
    type: http
    with:
      method: GET
      url: "__KIBANA_URL__/s/__KIBANA_SPACE__/api/detection_engine/rules?rule_id={{ inputs.rule_id }}"
      headers:
        Authorization: "ApiKey __KIBANA_API_KEY__"
        kbn-xsrf: "true"
    on-failure:
      continue: true

  - name: try_by_saved_object_id
    type: http
    condition: "{{ steps.try_by_rule_id.error != null }}"
    with:
      method: GET
      url: "__KIBANA_URL__/s/__KIBANA_SPACE__/api/detection_engine/rules?id={{ inputs.rule_id }}"
      headers:
        Authorization: "ApiKey __KIBANA_API_KEY__"
        kbn-xsrf: "true"
    on-failure:
      continue: true

  - name: output_rule
    type: console
    with:
      message: |
        {% assign rule = steps.try_by_saved_object_id.output.data | default: steps.try_by_rule_id.output.data %}
        Rule: {{ rule.name }}
        Rule ID: {{ rule.rule_id }}
        Saved Object ID: {{ rule.id }}
        Type: {{ rule.type }}
        Enabled: {{ rule.enabled }}
        Severity: {{ rule.severity }}
        Risk Score: {{ rule.risk_score }}
        Description: {{ rule.description }}
        Query: {{ rule.query }}
        Language: {{ rule.language }}
        Index: {{ rule.index }}
        Tags: {{ rule.tags | join: ", " }}
