# =============================================================================
# Workflow: List Detection Rules
# Category: security/detection
#
# Lists detection rules from the Kibana Detection Engine API with optional
# filtering. Uses explicit HTTP auth for subagent chain reliability.
#
# Author: Security Agent Mesh
# =============================================================================
name: List Detection Rules
description: List Elastic Security detection rules with optional filters.
enabled: true

tags:
  - agent-mesh
  - detection-engineering

triggers:
  - type: manual

inputs:
  - name: page
    type: number
    description: "Page number (1-based)"
    default: 1
  - name: per_page
    type: number
    description: "Results per page"
    default: 20
  - name: sort_field
    type: string
    description: "Field to sort by (e.g., name, enabled, severity)"
    default: "name"
  - name: sort_order
    type: string
    description: "Sort order: asc or desc"
    default: "asc"
  - name: search
    type: string
    description: "Free text search across rule names and descriptions"
    required: false

steps:

  - name: list_rules
    type: http
    with:
      method: GET
      url: "__KIBANA_URL__/s/__KIBANA_SPACE__/api/detection_engine/rules/_find?page={{ inputs.page }}&per_page={{ inputs.per_page }}&sort_field={{ inputs.sort_field }}&sort_order={{ inputs.sort_order }}"
      headers:
        Authorization: "ApiKey __KIBANA_API_KEY__"
        kbn-xsrf: "true"

  - name: output_summary
    type: console
    with:
      message: |
        Found {{ steps.list_rules.output.data.total }} rules (showing page {{ inputs.page }}, {{ inputs.per_page }} per page)
