# =============================================================================
# Workflow: Mark Alert as Acknowledged
# Category: security/detection
#
# Sets an alert status to acknowledged, indicating it is being
# investigated. Uses explicit HTTP auth for subagent chain reliability.
#
# Author: Security Agent Mesh
# =============================================================================
name: Mark Alert as Acknowledged
description: Set a security alert status to acknowledged.
enabled: true

tags:
  - agent-mesh
  - detection
  - triage

triggers:
  - type: manual

inputs:
  - name: alertid
    type: string
    description: "The alert ID to acknowledge"
    required: true

steps:

  - name: acknowledge_alert
    type: http
    with:
      method: POST
      url: "__KIBANA_URL__/s/__KIBANA_SPACE__/api/detection_engine/signals/status"
      headers:
        Content-Type: application/json
        Authorization: "ApiKey __KIBANA_API_KEY__"
        kbn-xsrf: "true"
      body:
        signal_ids:
          - "{{ inputs.alertid }}"
        status: acknowledged

  - name: confirm
    type: console
    with:
      message: "Alert {{ inputs.alertid }} acknowledged"
