# =============================================================================
# Workflow: 🚪 Mark Alert as Closed
# Category: security/detection
#
# This workflow YAML defines a manual trigger for marking a security alert as
# closed. It takes an input parameter, `alertid`, which defaults to "abc123".
# The workflow includes a single step that uses the Kibana API to set the
# status of the specified alert to "closed" with the reason labeled as
# "false_positive".
#
# Author: Elastic
# Created: 2025-11-07
# =============================================================================
version: "1"
name: 🚪 Mark Alert as Closed
enabled: true

# ---------------------------------------------------------------------------
# TRIGGERS
# ---------------------------------------------------------------------------
# Defines how and when this workflow is executed. Supported trigger types:
#   - manual: Run on-demand from the Kibana UI or API
#   - scheduled: Run on a recurring schedule (every: "5m" or rrule)
#   - alert: Run automatically when a security alert is triggered
# ---------------------------------------------------------------------------
triggers:
  - type: manual

# ---------------------------------------------------------------------------
# INPUTS
# ---------------------------------------------------------------------------
# Runtime parameters provided when the workflow is triggered. Each input
# can specify:
#   - name: Unique identifier for the input
#   - type: Data type (string, number, boolean, array, object)
#   - required: Whether the input must be provided (default: false)
#   - default: Default value if not provided
# Reference inputs in steps using {{ inputs.input_name }} syntax
# ---------------------------------------------------------------------------
inputs:
  - name: alertid
    type: string
    default: "abc123"

# ---------------------------------------------------------------------------
# STEPS
# ---------------------------------------------------------------------------
# The sequence of actions this workflow performs. Each step executes an
# action and can reference outputs from previous steps. Key properties:
#   - name: Unique identifier for referencing this step's output
#   - type: The action to perform (http, elasticsearch.search, foreach, etc.)
#   - with: Parameters passed to the action
#   - condition: Optional expression to conditionally run the step
#   - on-failure: Error handling configuration (retry, continue, etc.)
# Access step outputs using {{ steps.step_name.output.field }} syntax
# ---------------------------------------------------------------------------
steps:

  # -------------------------------------------------------------------------
  # STEP 1: kibana_SetAlertsStatus_step
  # -------------------------------------------------------------------------
  # Updates alert status using the Security Detection Engine API.
  # Valid statuses: "open" (new), "acknowledged" (in progress), "closed"
  # (resolved).
  # Status changes are audited and visible in the alert timeline.
  # Liquid syntax used:
  # - References workflow input parameter(s)
  # -------------------------------------------------------------------------
  - name: kibana_SetAlertsStatus_step
    type: kibana.SetAlertsStatus
    with:
      status: "closed"
      signal_ids: ["{{inputs.alertid}}"]
      reason: "false_positive"