# =============================================================================
# Workflow: Mark Alert as Closed
# Category: security/detection
#
# Closes a security alert. Uses explicit HTTP auth for subagent chain
# reliability.
#
# Author: Security Agent Mesh
# =============================================================================
name: Mark Alert as Closed
description: Close a security alert.
enabled: true

tags:
  - agent-mesh
  - detection
  - triage

triggers:
  - type: manual

inputs:
  - name: alertid
    type: string
    description: "The alert ID to close"
    required: true
  - name: reason
    type: string
    description: "Close reason: acknowledged, false_positive, other"
    default: "false_positive"

steps:

  - name: close_alert
    type: http
    with:
      method: POST
      url: "__KIBANA_URL__/s/__KIBANA_SPACE__/api/detection_engine/signals/status"
      headers:
        Content-Type: application/json
        Authorization: "ApiKey __KIBANA_API_KEY__"
        kbn-xsrf: "true"
      body:
        signal_ids:
          - "{{ inputs.alertid }}"
        status: closed

  - name: confirm
    type: console
    with:
      message: "Alert {{ inputs.alertid }} closed"
