# =============================================================================
# Workflow: Search Rules by MITRE Technique
# Category: security/detection
#
# Finds detection rules mapped to a specific MITRE ATT&CK technique ID.
# Uses explicit HTTP auth for subagent chain reliability.
#
# Author: Security Agent Mesh
# =============================================================================
name: Search Rules by MITRE Technique
description: Find detection rules mapped to a specific MITRE ATT&CK technique.
enabled: true

tags:
  - agent-mesh
  - detection-engineering
  - mitre

triggers:
  - type: manual

inputs:
  - name: technique_id
    type: string
    description: "MITRE ATT&CK technique ID (e.g., T1059, T1059.001)"
    required: true
  - name: per_page
    type: number
    description: "Maximum results to return"
    default: 50

steps:

  - name: search_rules
    type: http
    with:
      method: GET
      url: "__KIBANA_URL__/s/__KIBANA_SPACE__/api/detection_engine/rules/_find?per_page={{ inputs.per_page }}&search={{ inputs.technique_id }}"
      headers:
        Authorization: "ApiKey __KIBANA_API_KEY__"
        kbn-xsrf: "true"

  - name: output_results
    type: console
    with:
      message: |
        Found {{ steps.search_rules.output.data.total }} rules potentially matching technique {{ inputs.technique_id }}
