# =============================================================================
# Workflow: Update Detection Rule
# Category: security/detection
#
# Updates an existing detection rule via the Kibana Detection Engine PATCH API.
# Can modify query, severity, description, and other rule properties.
#
# Accepts either rule_id (slug) or saved object id (UUID) — tries rule_id
# first, falls back to id lookup, same pattern as get-rule-details.
#
# Author: Security Agent Mesh
# =============================================================================
name: Update Detection Rule
description: Update an existing detection rule's query, severity, description, or other properties.
enabled: true

tags:
  - agent-mesh
  - detection-engineering

triggers:
  - type: manual

inputs:
  - name: rule_id
    type: string
    description: "The rule_id (slug) or saved object id (UUID) of the rule to update"
    required: true
  - name: query
    type: string
    description: "Updated detection query (ES|QL, KQL, or EQL)"
    required: false
  - name: description
    type: string
    description: "Updated rule description"
    required: false
  - name: severity
    type: string
    description: "Updated severity: low, medium, high, critical"
    required: false
  - name: interval
    type: string
    description: "Updated run interval (e.g., 5m, 15m, 1h)"
    required: false
  - name: from
    type: string
    description: "Updated lookback period (e.g., now-6m, now-15m)"
    required: false
  - name: name
    type: string
    description: "Updated rule name"
    required: false

steps:

  # Try lookup by rule_id (slug) first
  - name: try_by_rule_id
    type: http
    with:
      method: GET
      url: "__KIBANA_URL__/s/__KIBANA_SPACE__/api/detection_engine/rules?rule_id={{ inputs.rule_id }}"
      headers:
        Authorization: "ApiKey __KIBANA_API_KEY__"
        kbn-xsrf: "true"
    on-failure:
      continue: true

  # Fall back to saved object id (UUID) if rule_id lookup failed
  - name: try_by_uuid
    type: http
    condition: "{{ steps.try_by_rule_id.error != null }}"
    with:
      method: GET
      url: "__KIBANA_URL__/s/__KIBANA_SPACE__/api/detection_engine/rules?id={{ inputs.rule_id }}"
      headers:
        Authorization: "ApiKey __KIBANA_API_KEY__"
        kbn-xsrf: "true"
    on-failure:
      continue: true

  - name: update_rule
    type: http
    with:
      method: PATCH
      url: "__KIBANA_URL__/s/__KIBANA_SPACE__/api/detection_engine/rules"
      headers:
        Content-Type: application/json
        Authorization: "ApiKey __KIBANA_API_KEY__"
        kbn-xsrf: "true"
      body:
        id: "{{ steps.try_by_uuid.output.data.id | default: steps.try_by_rule_id.output.data.id }}"
        query: "{{ inputs.query | default: steps.try_by_rule_id.output.data.query | default: steps.try_by_uuid.output.data.query }}"
        description: "{{ inputs.description | default: steps.try_by_rule_id.output.data.description | default: steps.try_by_uuid.output.data.description }}"
        severity: "{{ inputs.severity | default: steps.try_by_rule_id.output.data.severity | default: steps.try_by_uuid.output.data.severity }}"
        interval: "{{ inputs.interval | default: steps.try_by_rule_id.output.data.interval | default: steps.try_by_uuid.output.data.interval }}"
        from: "{{ inputs.from | default: steps.try_by_rule_id.output.data.from | default: steps.try_by_uuid.output.data.from }}"
    on-failure:
      continue: true

  - name: confirm
    type: console
    with:
      message: |
        Rule updated:
        Name: {{ steps.update_rule.output.data.name }}
        ID: {{ steps.update_rule.output.data.id }}
        Rule ID: {{ steps.update_rule.output.data.rule_id }}
        Severity: {{ steps.update_rule.output.data.severity }}
        Enabled: {{ steps.update_rule.output.data.enabled }}
