# =============================================================================
# Workflow: Create Caldera Ability
# Category: integrations/caldera
#
# The workflow YAML defines a process for creating a custom ability in MITRE
# Caldera, triggered manually with specified inputs such as ability name,
# description, and commands for Linux and Windows. It validates the provided
# commands and constructs an HTTP request to the Caldera API to create the
# ability, handling both Linux and Windows commands, or both if provided. The
# workflow includes error handling with retry logic and outputs the results
# to the console.
#
# Author: Elastic
# Created: 2025-11-13
# =============================================================================
name: Create Caldera Ability
description: Creates a custom ability in MITRE Caldera with the specified attack payload
enabled: true

# ---------------------------------------------------------------------------
# TRIGGERS
# ---------------------------------------------------------------------------
# Defines how and when this workflow is executed. Supported trigger types:
#   - manual: Run on-demand from the Kibana UI or API
#   - scheduled: Run on a recurring schedule (every: "5m" or rrule)
#   - alert: Run automatically when a security alert is triggered
# ---------------------------------------------------------------------------
triggers:
  - type: manual

# ---------------------------------------------------------------------------
# INPUTS
# ---------------------------------------------------------------------------
# Runtime parameters provided when the workflow is triggered. Each input
# can specify:
#   - name: Unique identifier for the input
#   - type: Data type (string, number, boolean, array, object)
#   - required: Whether the input must be provided (default: false)
#   - default: Default value if not provided
# Reference inputs in steps using {{ inputs.input_name }} syntax
# ---------------------------------------------------------------------------
inputs:
  - name: ability_name
    description: Descriptive name for the ability
    required: true
    type: string
  - name: ability_description
    description: Brief purpose description of the ability
    required: true
    type: string
  - name: tactic
    description: MITRE ATT&CK tactic
    required: false
    type: string
  - name: technique_name
    description: MITRE ATT&CK technique name
    required: false
    type: string
  - name: technique_id
    description: MITRE ATT&CK technique ID (e.g., "T1021.002")
    required: false
    type: string
  - name: linux_command
    description: Bash command for Linux target
    required: false
    type: string
  - name: windows_command
    description: PowerShell command for Windows target
    required: false
    type: string

# ---------------------------------------------------------------------------
# CONSTANTS
# ---------------------------------------------------------------------------
# Reusable configuration values defined once and referenced throughout the
# workflow using {{ consts.key_name }} syntax. Use constants for:
#   - API endpoints and URLs
#   - API keys and authentication tokens (use secrets in production)
#   - Environment-specific configuration
#   - Values that may need to change across environments
# ---------------------------------------------------------------------------
consts:
  caldera_base_url: https://example.com:8888
  caldera_api_key: API-KEY

# ---------------------------------------------------------------------------
# STEPS
# ---------------------------------------------------------------------------
# The sequence of actions this workflow performs. Each step executes an
# action and can reference outputs from previous steps. Key properties:
#   - name: Unique identifier for referencing this step's output
#   - type: The action to perform (http, elasticsearch.search, foreach, etc.)
#   - with: Parameters passed to the action
#   - condition: Optional expression to conditionally run the step
#   - on-failure: Error handling configuration (retry, continue, etc.)
# Access step outputs using {{ steps.step_name.output.field }} syntax
# ---------------------------------------------------------------------------
steps:

  # -------------------------------------------------------------------------
  # STEP 1: validate_commands
  # -------------------------------------------------------------------------
  # Evaluates a condition and executes different steps based on the result.
  # Enables dynamic workflow behavior based on runtime data.
  # -------------------------------------------------------------------------
  - name: validate_commands
    type: if
    condition: inputs.linux_command:* or inputs.windows_command:*
    steps:

      # -------------------------------------------------------------------------
      # STEP 2: build_request_body
      # -------------------------------------------------------------------------
      # Evaluates a condition and executes different steps based on the result.
      # Enables dynamic workflow behavior based on runtime data.
      # -------------------------------------------------------------------------
      - name: build_request_body
        type: if
        condition: inputs.linux_command:* and inputs.windows_command:*
        steps:

          # -------------------------------------------------------------------------
          # STEP 3: create_ability_both
          # -------------------------------------------------------------------------
          # Creates or retrieves Caldera abilities (attack techniques).
          # Liquid syntax used:
          # - References workflow input parameter(s)
          # - References workflow constant(s)
          # -------------------------------------------------------------------------
          - name: create_ability_both
            type: http
            with:
              url: "{{ consts.caldera_base_url }}/api/v2/abilities"
              method: POST
              headers:
                KEY: "{{ consts.caldera_api_key }}"
                Content-Type: application/json
              body:
                tactic: "{{ inputs.tactic }}"
                executors:

                  # -------------------------------------------------------------------------
                  # STEP 4: sh
                  # -------------------------------------------------------------------------
                  # Executes the specified action with the configured parameters.
                  # Liquid syntax used:
                  # - References workflow input parameter(s)
                  # -------------------------------------------------------------------------
                  - name: sh
                    platform: linux
                    command: "{{ inputs.linux_command }}"
                    code: null
                    language: null
                    build_target: null
                    payloads: []
                    uploads: []
                    timeout: 60
                    parsers: []
                    cleanup: []
                    variations: []
                    additional_info: {}

                  # -------------------------------------------------------------------------
                  # STEP 5: psh
                  # -------------------------------------------------------------------------
                  # Executes the specified action with the configured parameters.
                  # Liquid syntax used:
                  # - References workflow input parameter(s)
                  # -------------------------------------------------------------------------
                  - name: psh
                    platform: windows
                    command: "{{ inputs.windows_command }}"
                    code: null
                    language: null
                    build_target: null
                    payloads: []
                    uploads: []
                    timeout: 60
                    parsers: []
                    cleanup: []
                    variations: []
                    additional_info: {}
                requirements: []
                privilege: ""
                repeatable: false
                buckets:
                  - "{{ inputs.tactic }}"
                additional_info: {}
                access: {}
                singleton: false
                plugin: ""
                delete_payload: true
            on-failure:
              retry:
                max-attempts: 2
                delay: 3s

          # -------------------------------------------------------------------------
          # STEP 6: output_both
          # -------------------------------------------------------------------------
          # Outputs a message to the workflow execution log for visibility.
          # Liquid syntax used:
          # - References output from previous step(s)
          # -------------------------------------------------------------------------
          - name: output_both
            type: console
            with:
              message: ${{ steps.create_ability_both.output.data }}
        else:

          # -------------------------------------------------------------------------
          # STEP 7: check_linux_only
          # -------------------------------------------------------------------------
          # Evaluates a condition and executes different steps based on the result.
          # Enables dynamic workflow behavior based on runtime data.
          # -------------------------------------------------------------------------
          - name: check_linux_only
            type: if
            condition: inputs.linux_command:*
            steps:

              # -------------------------------------------------------------------------
              # STEP 8: create_ability_linux
              # -------------------------------------------------------------------------
              # Creates or retrieves Caldera abilities (attack techniques).
              # Liquid syntax used:
              # - References workflow input parameter(s)
              # - References workflow constant(s)
              # -------------------------------------------------------------------------
              - name: create_ability_linux
                type: http
                with:
                  url: "{{ consts.caldera_base_url }}/api/v2/abilities"
                  method: POST
                  headers:
                    KEY: "{{ consts.caldera_api_key }}"
                    Content-Type: application/json
                  body:
                    tactic: "{{ inputs.tactic }}"
                    technique_name: "{{ inputs.technique_name }}"
                    technique_id: "{{ inputs.technique_id }}"
                    name: "{{ inputs.ability_name }}"
                    description: "{{ inputs.ability_description }}"
                    executors:

                      # -------------------------------------------------------------------------
                      # STEP 9: sh
                      # -------------------------------------------------------------------------
                      # Executes the specified action with the configured parameters.
                      # Liquid syntax used:
                      # - References workflow input parameter(s)
                      # -------------------------------------------------------------------------
                      - name: sh
                        platform: linux
                        command: "{{ inputs.linux_command }}"
                        code: null
                        language: null
                        build_target: null
                        payloads: []
                        uploads: []
                        timeout: 60
                        parsers: []
                        cleanup: []
                        variations: []
                        additional_info: {}
                    requirements: []
                    privilege: ""
                    repeatable: false
                    buckets:
                      - "{{ inputs.tactic }}"
                    additional_info: {}
                    access: {}
                    singleton: false
                    plugin: ""
                    delete_payload: true
                on-failure:
                  retry:
                    max-attempts: 2
                    delay: 3s

              # -------------------------------------------------------------------------
              # STEP 10: output_linux
              # -------------------------------------------------------------------------
              # Outputs a message to the workflow execution log for visibility.
              # Liquid syntax used:
              # - References output from previous step(s)
              # -------------------------------------------------------------------------
              - name: output_linux
                type: console
                with:
                  message: ${{ steps.create_ability_linux.output.data }}
            else:

              # -------------------------------------------------------------------------
              # STEP 11: create_ability_windows
              # -------------------------------------------------------------------------
              # Creates or retrieves Caldera abilities (attack techniques).
              # Liquid syntax used:
              # - References workflow input parameter(s)
              # - References workflow constant(s)
              # -------------------------------------------------------------------------
              - name: create_ability_windows
                type: http
                with:
                  url: "{{ consts.caldera_base_url }}/api/v2/abilities"
                  method: POST
                  headers:
                    KEY: "{{ consts.caldera_api_key }}"
                    Content-Type: application/json
                  body:
                    tactic: "{{ inputs.tactic }}"
                    technique_name: "{{ inputs.technique_name }}"
                    technique_id: "{{ inputs.technique_id }}"
                    name: "{{ inputs.ability_name }}"
                    description: "{{ inputs.ability_description }}"
                    executors:

                      # -------------------------------------------------------------------------
                      # STEP 12: psh
                      # -------------------------------------------------------------------------
                      # Executes the specified action with the configured parameters.
                      # Liquid syntax used:
                      # - References workflow input parameter(s)
                      # -------------------------------------------------------------------------
                      - name: psh
                        platform: windows
                        command: "{{ inputs.windows_command }}"
                        code: null
                        language: null
                        build_target: null
                        payloads: []
                        uploads: []
                        timeout: 60
                        parsers: []
                        cleanup: []
                        variations: []
                        additional_info: {}
                    requirements: []
                    privilege: ""
                    repeatable: false
                    buckets:
                      - "{{ inputs.tactic }}"
                    additional_info: {}
                    access: {}
                    singleton: false
                    plugin: ""
                    delete_payload: true
                on-failure:
                  retry:
                    max-attempts: 2
                    delay: 3s

              # -------------------------------------------------------------------------
              # STEP 13: output_windows
              # -------------------------------------------------------------------------
              # Outputs a message to the workflow execution log for visibility.
              # Liquid syntax used:
              # - References output from previous step(s)
              # -------------------------------------------------------------------------
              - name: output_windows
                type: console
                with:
                  message: ${{ steps.create_ability_windows.output.data }}