# =============================================================================
# Workflow: Create Caldera Adversary
# Category: integrations/caldera
#
# The workflow YAML defines a process for creating a new adversary profile in
# MITRE Caldera, including a specified collection of abilities to be executed
# in a defined order. It requires inputs such as the adversary's name, a
# description, and an array of ability IDs. The workflow is triggered
# manually and includes steps to send an HTTP POST request to the Caldera
# API, with error handling that allows for retries. Finally, it formats and
# outputs the response data from the API call.
#
# Author: Elastic
# Created: 2025-11-13
# =============================================================================
name: Create Caldera Adversary
enabled: true
description:
  Creates a new adversary profile in MITRE Caldera with a collection
  of abilities/attacks to be executed in specified order, returns as an object

# ---------------------------------------------------------------------------
# CONSTANTS
# ---------------------------------------------------------------------------
# Reusable configuration values defined once and referenced throughout the
# workflow using {{ consts.key_name }} syntax. Use constants for:
#   - API endpoints and URLs
#   - API keys and authentication tokens (use secrets in production)
#   - Environment-specific configuration
#   - Values that may need to change across environments
# ---------------------------------------------------------------------------
consts:
  caldera_base_url: http://example.com:8888
  caldera_api_key: API-key

# ---------------------------------------------------------------------------
# INPUTS
# ---------------------------------------------------------------------------
# Runtime parameters provided when the workflow is triggered. Each input
# can specify:
#   - name: Unique identifier for the input
#   - type: Data type (string, number, boolean, array, object)
#   - required: Whether the input must be provided (default: false)
#   - default: Default value if not provided
# Reference inputs in steps using {{ inputs.input_name }} syntax
# ---------------------------------------------------------------------------
inputs:
  - name: adversary_name
    type: string
    description: The name of the adversary profile to create
    required: true
  - name: description
    type: string
    description: A short and concise description about the adversary collection and what it does
  - name: ability_ids
    type: array
    description: Array of ability ID's that will be used in the adversary, in the order of execution
    required: true

# ---------------------------------------------------------------------------
# TRIGGERS
# ---------------------------------------------------------------------------
# Defines how and when this workflow is executed. Supported trigger types:
#   - manual: Run on-demand from the Kibana UI or API
#   - scheduled: Run on a recurring schedule (every: "5m" or rrule)
#   - alert: Run automatically when a security alert is triggered
# ---------------------------------------------------------------------------
triggers:
  - type: manual

# ---------------------------------------------------------------------------
# STEPS
# ---------------------------------------------------------------------------
# The sequence of actions this workflow performs. Each step executes an
# action and can reference outputs from previous steps. Key properties:
#   - name: Unique identifier for referencing this step's output
#   - type: The action to perform (http, elasticsearch.search, foreach, etc.)
#   - with: Parameters passed to the action
#   - condition: Optional expression to conditionally run the step
#   - on-failure: Error handling configuration (retry, continue, etc.)
# Access step outputs using {{ steps.step_name.output.field }} syntax
# ---------------------------------------------------------------------------
steps:

  # -------------------------------------------------------------------------
  # STEP 1: create_adversary
  # -------------------------------------------------------------------------
  # Manages Caldera adversary profiles containing collections of abilities.
  # Includes retry logic to handle transient failures gracefully.
  # Liquid syntax used:
  # - References workflow input parameter(s)
  # - References workflow constant(s)
  # -------------------------------------------------------------------------
  - name: create_adversary
    type: http
    with:
      url: "{{ consts.caldera_base_url }}/api/v2/adversaries"
      method: POST
      headers:
        KEY: "{{ consts.caldera_api_key }}"
        Content-Type: application/json
      body:
        name: "{{ inputs.adversary_name }}"
        description: "{{ inputs.description }}"
        atomic_ordering: ${{ inputs.ability_ids }}
        objective: ""
        tags: []
        plugin: ""
    on-failure:
      retry:
        max-attempts: 2
        delay: 3s

  # -------------------------------------------------------------------------
  # STEP 2: format_output
  # -------------------------------------------------------------------------
  # Formats and displays the results in a human-readable report format.
  # This output is visible in the workflow execution logs.
  # Liquid syntax used:
  # - References output from previous step(s)
  # -------------------------------------------------------------------------
  - name: format_output
    type: console
    with:
      message: ${{ steps.create_adversary.output.data }}