# =============================================================================
# Workflow: Mesh Automated Triaging
# Category: security/response
#
# Alert-triggered triage that bridges security alerts into the agent mesh.
# When an alert fires, this workflow:
#   1. Creates an investigation context for state tracking
#   2. Looks up the L1 Triage Analyst in the agent registry
#   3. Routes the alert to L1 with full context (no alert re-search needed)
#   4. Records findings for audit
#
# L1 owns the escalation decision — if the alert warrants deeper
# investigation, L1 calls L2 via its Call Subagent tool autonomously.
# The workflow does NOT force an L2 call.
#
# Uses event.alerts[0] to access the first alert from the trigger
# payload (foreach on event.alerts fails due to payload size).
#
# Author: Security Agent Mesh
# =============================================================================
name: Mesh Automated Triaging
description: Alert-triggered triage that creates an investigation and routes to the analyst agent mesh.
enabled: true

tags:
  - agent-mesh
  - triage
  - response

triggers:
  - type: alert

consts:
  es_url: "__ES_URL__"
  es_api_key: "__ES_API_KEY__"
  investigation_index: "investigation-contexts"
  registry_index: "agent-registry"
  alerts_index: ".alerts-security.alerts-*"

steps:

  - name: create_investigation
    type: http
    with:
      method: POST
      url: "{{ consts.es_url }}/{{ consts.investigation_index }}/_doc"
      headers:
        Content-Type: application/json
        Authorization: "ApiKey {{ consts.es_api_key }}"
      body:
        investigation_id: "inv-{{ event.alerts[0]._id }}"
        title: "Alert Triage: {{ event.alerts[0].kibana.alert.rule.name }}"
        trigger_type: "alert"
        trigger_ref: "{{ event.alerts[0]._id }}"
        status: "open"
        risk_tier: "tier_0"
        assigned_agent: ""
        summary: ""
        semantic_summary: "Alert triage for {{ event.alerts[0].kibana.alert.rule.name }}. {{ event.alerts[0].kibana.alert.rule.description }}"
        evidence: []
        actions_taken: []
        pending_actions: []
        tags:
          - alert-triage
          - automated
        created_at: "{{ 'now' | date: '%Y-%m-%dT%H:%M:%SZ' }}"
        updated_at: "{{ 'now' | date: '%Y-%m-%dT%H:%M:%SZ' }}"

  - name: log_investigation_created
    type: console
    with:
      message: "Investigation created for alert {{ event.alerts[0]._id }}: {{ event.alerts[0].kibana.alert.rule.name }}"

  - name: find_analyst_agent
    type: http
    with:
      method: POST
      url: "{{ consts.es_url }}/{{ consts.registry_index }}/_search"
      headers:
        Content-Type: application/json
        Authorization: "ApiKey {{ consts.es_api_key }}"
      body:
        size: 1
        query:
          bool:
            must:
              - term:
                  status: "active"
              - term:
                  domain: "triage"

  - name: update_assignment
    type: http
    on-failure:
      continue: true
    with:
      method: POST
      url: "{{ consts.es_url }}/{{ consts.investigation_index }}/_update/{{ steps.create_investigation.output.data._id }}"
      headers:
        Content-Type: application/json
        Authorization: "ApiKey {{ consts.es_api_key }}"
      body:
        doc:
          assigned_agent: "{{ steps.find_analyst_agent.output.data.hits.hits[0]._source.agent_id }}"
          status: "investigating"
          updated_at: "{{ 'now' | date: '%Y-%m-%dT%H:%M:%SZ' }}"

  - name: invoke_analyst
    type: http
    on-failure:
      continue: true
    with:
      method: POST
      url: "__KIBANA_URL__/s/__KIBANA_SPACE__/api/agent_builder/converse"
      headers:
        Content-Type: application/json
        Authorization: "ApiKey __KIBANA_API_KEY__"
        kbn-xsrf: "true"
      body:
        agent_id: "{{ steps.find_analyst_agent.output.data.hits.hits[0]._source.agent_id }}"
        connector_id: "__LLM_CONNECTOR_ID__"
        input: |
          Triage this security alert. Investigation document ID: {{ steps.create_investigation.output.data._id }}

          IMPORTANT: Do NOT search for this alert using Security Alerts — all context is provided below.

          Alert Rule: {{ event.alerts[0].kibana.alert.rule.name }}
          Alert ID: {{ event.alerts[0]._id }}
          Severity: {{ event.alerts[0].kibana.alert.severity }}
          Risk Score: {{ event.alerts[0].kibana.alert.risk_score }}
          Host: {{ event.alerts[0].host.name }}
          Rule Description: {{ event.alerts[0].kibana.alert.rule.description }}

          The L2 Investigation Analyst agent_id is: security-mesh.l2-investigation-analyst

          Instructions:
          1. Analyse the alert context above — determine true positive or false positive
          2. Search for similar past incidents and applicable playbooks using Semantic Knowledge Search
          3. Add your findings as evidence to investigation {{ steps.create_investigation.output.data._id }}
          4. If true positive: tag the alert, create a case, link the alert to it, and add a case comment with your triage summary
          5. If false positive: tag the alert, close it, and document why
          6. If this is a true positive requiring deeper investigation, escalate to the L2 Investigation Analyst via Call Subagent — pass the case ID, alert details, and your analysis so L2 can continue on the same case
    timeout: 600s

  - name: log_analyst_response
    type: console
    on-failure:
      continue: true
    with:
      message: "L1 agent response: {{ steps.invoke_analyst.output.data.response.message }}"

  - name: record_analyst_evidence
    type: http
    on-failure:
      continue: true
    with:
      method: POST
      url: "{{ consts.es_url }}/{{ consts.investigation_index }}/_update/{{ steps.create_investigation.output.data._id }}"
      headers:
        Content-Type: application/json
        Authorization: "ApiKey {{ consts.es_api_key }}"
      body:
        script:
          source: |
            if (ctx._source.evidence == null) { ctx._source.evidence = []; }
            ctx._source.evidence.add(params.entry);
            ctx._source.updated_at = params.now;
          params:
            entry:
              agent_id: "{{ steps.find_analyst_agent.output.data.hits.hits[0]._source.agent_id }}"
              timestamp: "{{ 'now' | date: '%Y-%m-%dT%H:%M:%SZ' }}"
              evidence_type: "finding"
              content: "{{ steps.invoke_analyst.output.data.response.message }}"
              confidence: 0.8
              references:
                - "{{ event.alerts[0]._id }}"
            now: "{{ 'now' | date: '%Y-%m-%dT%H:%M:%SZ' }}"
