# =============================================================================
# Workflow: create JIRA ticket
# Category: integrations/jira
#
# This workflow YAML defines a process for creating a JIRA ticket through an
# API. It includes inputs for the ticket's summary and description, with
# default values provided. The workflow is triggered manually and consists of
# a single step that sends an HTTP POST request to the JIRA service desk API,
# including necessary headers and body parameters for the ticket creation.
#
# Author: Elastic
# Created: 2025-11-20
# =============================================================================
name: create JIRA ticket
enabled: true

# ---------------------------------------------------------------------------
# INPUTS
# ---------------------------------------------------------------------------
# Runtime parameters provided when the workflow is triggered. Each input
# can specify:
#   - name: Unique identifier for the input
#   - type: Data type (string, number, boolean, array, object)
#   - required: Whether the input must be provided (default: false)
#   - default: Default value if not provided
# Reference inputs in steps using {{ inputs.input_name }} syntax
# ---------------------------------------------------------------------------
inputs:
  - name: summary
    default: Ticket opened by AutoRemedy
    type: string
  - name: description
    default: This ticket was opened by AutoRemedy using APIs
    type: string

# ---------------------------------------------------------------------------
# CONSTANTS
# ---------------------------------------------------------------------------
# Reusable configuration values defined once and referenced throughout the
# workflow using {{ consts.key_name }} syntax. Use constants for:
#   - API endpoints and URLs
#   - API keys and authentication tokens (use secrets in production)
#   - Environment-specific configuration
#   - Values that may need to change across environments
# ---------------------------------------------------------------------------
consts:
  url: https://your-company.atlassian.net
  user: >-
    user@example.com:ATATT3xFfGF0_YOUR-API-KEY-HERE_qEH01VUr2BW-M27Wuws5ZfkLz_e7IK4xEA-LOguQRD2_kYgiqN-W5RIqWoO4ADqZRNCSK7tKE49zOM-YOUR-API-KEY-HERE

# ---------------------------------------------------------------------------
# TRIGGERS
# ---------------------------------------------------------------------------
# Defines how and when this workflow is executed. Supported trigger types:
#   - manual: Run on-demand from the Kibana UI or API
#   - scheduled: Run on a recurring schedule (every: "5m" or rrule)
#   - alert: Run automatically when a security alert is triggered
# ---------------------------------------------------------------------------
triggers:
  - type: manual

# ---------------------------------------------------------------------------
# STEPS
# ---------------------------------------------------------------------------
# The sequence of actions this workflow performs. Each step executes an
# action and can reference outputs from previous steps. Key properties:
#   - name: Unique identifier for referencing this step's output
#   - type: The action to perform (http, elasticsearch.search, foreach, etc.)
#   - with: Parameters passed to the action
#   - condition: Optional expression to conditionally run the step
#   - on-failure: Error handling configuration (retry, continue, etc.)
# Access step outputs using {{ steps.step_name.output.field }} syntax
# ---------------------------------------------------------------------------
steps:

  # -------------------------------------------------------------------------
  # STEP 1: open ticket
  # -------------------------------------------------------------------------
  # Sends data to an external API endpoint via HTTP POST request.
  # Liquid syntax used:
  # - References workflow input parameter(s)
  # - References workflow constant(s)
  # -------------------------------------------------------------------------
  - name: open ticket
    type: http
    with:
      url: '{{consts.url}}'
      method: POST
      timeout: 30s
      headers:
        Accept: application/json
        Content-Type: application/json
        Authorization: secret
      body:
        serviceDeskId: '1'
        requestTypeId: '1'
        raiseOnBehalfOf: user@example.com
        requestFieldValues:
          summary: '{{inputs.summary}}'
          description: '{{inputs.description}}'
