# =============================================================================
# Workflow: Log Decision
# Category: governance
#
# Records a machine-readable decision record in the investigation context.
# Every action (approved, denied, or auto-approved) should be logged for
# audit trail, replay, and scoring.
#
# Author: Security Agent Mesh
# =============================================================================
name: Log Decision
description: Record an action decision in the investigation context for audit.
enabled: true

tags:
  - agent-mesh
  - governance

triggers:
  - type: manual

inputs:
  - name: document_id
    type: string
    description: "The Elasticsearch document _id of the investigation context (from the investigation-contexts index). This is NOT the case ID — use the _id returned when the investigation was created."
    required: true
  - name: agent_id
    type: string
    description: "Agent that performed or requested the action"
    required: true
  - name: action_type
    type: string
    description: "Type of action taken"
    required: true
  - name: target
    type: string
    description: "What the action targeted"
    required: true
  - name: approved_by
    type: string
    description: "Who approved: 'auto' for Tier 0, agent_id for Tier 1, human identifier for Tier 2"
    required: true
  - name: result
    type: string
    description: "Outcome of the action (success, failed, denied, pending)"
    required: true
  - name: risk_tier
    type: string
    description: "Risk tier of the action"
    required: true

consts:
  es_url: "__ES_URL__"
  es_api_key: "__ES_API_KEY__"
  index_name: "investigation-contexts"

steps:

  - name: log_action
    type: http
    with:
      method: POST
      url: "{{ consts.es_url }}/{{ consts.index_name }}/_update/{{ inputs.document_id }}"
      headers:
        Content-Type: application/json
        Authorization: "ApiKey {{ consts.es_api_key }}"
      body:
        script:
          source: |
            if (ctx._source.actions_taken == null) { ctx._source.actions_taken = []; }
            ctx._source.actions_taken.add(params.record);
            ctx._source.updated_at = params.now;
          params:
            record:
              agent_id: "{{ inputs.agent_id }}"
              action_type: "{{ inputs.action_type }}"
              target: "{{ inputs.target }}"
              timestamp: "{{ 'now' | date: '%Y-%m-%dT%H:%M:%SZ' }}"
              approved_by: "{{ inputs.approved_by }}"
              result: "{{ inputs.result }}"
              risk_tier: "{{ inputs.risk_tier }}"
            now: "{{ 'now' | date: '%Y-%m-%dT%H:%M:%SZ' }}"

  - name: confirm
    type: console
    with:
      message: "Decision logged: {{ inputs.action_type }} on {{ inputs.target }} — {{ inputs.result }} (approved by {{ inputs.approved_by }})"
