# =============================================================================
# Workflow: Request Approval
# Category: governance
#
# Adds a structured approval request as a comment on an existing case.
# Used when a Tier 2 action needs human authorisation. The comment
# includes the action details, justification, risk tier, and clear
# approve/deny instructions. Humans review and respond directly in
# the case — no separate approval case needed.
#
# Author: Security Agent Mesh
# =============================================================================
name: Request Approval
description: Request human approval for a Tier 2 governance-gated action on an existing case.
enabled: true

tags:
  - agent-mesh
  - governance

triggers:
  - type: manual

inputs:
  - name: case_id
    type: string
    description: "The existing case ID to add the approval request to"
    required: true
  - name: action_type
    type: string
    description: "The action requiring approval (e.g., isolate_host)"
    required: true
  - name: recommending_agent
    type: string
    description: "Agent ID that recommended this action"
    required: true
  - name: justification
    type: string
    description: "Why this action should be taken"
    required: true
  - name: risk_tier
    type: string
    description: "Risk tier of the action"
    required: true
  - name: target
    type: string
    description: "What the action targets (hostname, endpoint ID, rule ID, etc.)"
    required: true

steps:

  - name: add_approval_comment
    type: http
    with:
      method: POST
      url: "__KIBANA_URL__/s/__KIBANA_SPACE__/api/cases/{{ inputs.case_id }}/comments"
      headers:
        Content-Type: application/json
        Authorization: "ApiKey __KIBANA_API_KEY__"
        kbn-xsrf: "true"
        elastic-api-version: "2023-10-31"
      body:
        type: "user"
        comment: |
          ## Tier 2 Action — Human Approval Required

          | Field | Value |
          |-------|-------|
          | **Action** | {{ inputs.action_type }} |
          | **Target** | {{ inputs.target }} |
          | **Risk Tier** | {{ inputs.risk_tier }} |
          | **Recommended by** | {{ inputs.recommending_agent }} |

          ### Justification

          {{ inputs.justification }}

          ---

          **To approve:** Reply with APPROVED
          **To deny:** Reply with DENIED and the reason
        owner: "securitySolution"

  - name: confirm
    type: console
    with:
      message: "Approval requested on case {{ inputs.case_id }} for {{ inputs.action_type }} targeting {{ inputs.target }}"
