# =============================================================================
# Workflow: rootCauseFromDiscover
# Category: security/enrichment
#
# The workflow named "rootCauseFromDiscover" is designed to enrich logs
# containing exception messages by analyzing them for root causes using a
# language model. It is triggered manually and requires an index and ID as
# inputs. The process involves analyzing the exception stack trace to
# identify the root cause in a concise manner and then updating the relevant
# log entry in Elasticsearch with the findings.
#
# Author: Elastic
# Created: 2025-11-19
# =============================================================================
name: rootCauseFromDiscover
description: Enrich logs that have exception message with rootCause using LLM
enabled: true

# ---------------------------------------------------------------------------
# TRIGGERS
# ---------------------------------------------------------------------------
# Defines how and when this workflow is executed. Supported trigger types:
#   - manual: Run on-demand from the Kibana UI or API
#   - scheduled: Run on a recurring schedule (every: "5m" or rrule)
#   - alert: Run automatically when a security alert is triggered
# ---------------------------------------------------------------------------
triggers:
  - type: manual

# ---------------------------------------------------------------------------
# INPUTS
# ---------------------------------------------------------------------------
# Runtime parameters provided when the workflow is triggered. Each input
# can specify:
#   - name: Unique identifier for the input
#   - type: Data type (string, number, boolean, array, object)
#   - required: Whether the input must be provided (default: false)
#   - default: Default value if not provided
# Reference inputs in steps using {{ inputs.input_name }} syntax
# ---------------------------------------------------------------------------
inputs:
  - name: .index
    required: true
    type: string
  - name: .id
    required: true
    type: string

# ---------------------------------------------------------------------------
# STEPS
# ---------------------------------------------------------------------------
# The sequence of actions this workflow performs. Each step executes an
# action and can reference outputs from previous steps. Key properties:
#   - name: Unique identifier for referencing this step's output
#   - type: The action to perform (http, elasticsearch.search, foreach, etc.)
#   - with: Parameters passed to the action
#   - condition: Optional expression to conditionally run the step
#   - on-failure: Error handling configuration (retry, continue, etc.)
# Access step outputs using {{ steps.step_name.output.field }} syntax
# ---------------------------------------------------------------------------
steps:

  # -------------------------------------------------------------------------
  # STEP 1: analyze_exception_root_cause
  # -------------------------------------------------------------------------
  # Executes the inference.completion action with the configured parameters.
  # Liquid syntax used:
  # - References workflow input parameter(s)
  # -------------------------------------------------------------------------
  - name: analyze_exception_root_cause
    type: inference.completion
    connector-id: openai
    with:
      input: |
        You are a senior software engineer experienced in debugging and root cause analysis.
        Your task is to analyze the given **exception stack trace** and explain the **most likely root cause** in 2–3 sentences.

        INSTRUCTIONS:
        - Focus on identifying what triggered the error and where it originated.
        - Use plain, direct language suitable for engineers.
        - Avoid generic advice; be specific to the error pattern and stack trace context.
        - Output should be only 2–3 sentences — no greetings or extra formatting.

        Here is the stack trace:
        exception message: {{ inputs.fields['exception.message'] }}
        exception trace: {{ inputs.fields['error.stacktrace'] }}


  # -------------------------------------------------------------------------
  # STEP 2: enrich
  # -------------------------------------------------------------------------
  # Executes a search query against one or more Elasticsearch indices.
  # Output: {{ steps.enrich.output.hits }} contains matching documents.
  # Liquid syntax used:
  # - References output from previous step(s)
  # - References workflow input parameter(s)
  # -------------------------------------------------------------------------
  - name: enrich
    type: elasticsearch.update
    with:
      index: "{{ inputs._index }}"
      id: "{{ inputs._id }}"
      doc_as_upsert: true
      doc:
        attributes:
          rootCause: ${{ steps.analyze_exception_root_cause.output.0.result }}
