# =============================================================================
# Workflow: VirusTotal — File Hash Report
# Category: security/enrichment
#
# Retrieves a file analysis report from VirusTotal given a file hash
# (MD5, SHA-1, or SHA-256). Returns detection results, reputation scores,
# and contextual threat data from 70+ antivirus engines.
#
# Free tier: 4 requests/min, 500 requests/day
# API docs: https://docs.virustotal.com/reference/file-info
# =============================================================================

name: "VirusTotal — File Hash Report"
description: "Get a VirusTotal file report by MD5, SHA-1, or SHA-256 hash"

triggers:
  - type: manual

consts:
  vt_api_key: YOUR-VT-API-KEY

inputs:
  - name: file_hash
    type: string
    description: "File hash to look up (MD5, SHA-1, or SHA-256)"
    required: true

steps:
  - name: lookup_hash
    type: http
    with:
      url: "https://www.virustotal.com/api/v3/files/{{ inputs.file_hash }}"
      method: GET
      headers:
        x-apikey: "{{ consts.vt_api_key }}"
        Accept: application/json
      timeout: 30s
    on-failure:
      retry:
        max-attempts: 2
        delay: 5s
      continue: true

  - name: format_report
    type: console
    with:
      message: |
        === VirusTotal File Report ===
        Hash: {{ inputs.file_hash }}
        
        Detection: {{ steps.lookup_hash.output.data.data.attributes.last_analysis_stats.malicious }}/{{ steps.lookup_hash.output.data.data.attributes.last_analysis_stats.malicious | plus: steps.lookup_hash.output.data.data.attributes.last_analysis_stats.undetected }} engines flagged as malicious
        Reputation: {{ steps.lookup_hash.output.data.data.attributes.reputation }}
        File type: {{ steps.lookup_hash.output.data.data.attributes.type_description }}
        File size: {{ steps.lookup_hash.output.data.data.attributes.size }} bytes
        First seen: {{ steps.lookup_hash.output.data.data.attributes.first_submission_date }}
        Last analysed: {{ steps.lookup_hash.output.data.data.attributes.last_analysis_date }}
        
        Names: {{ steps.lookup_hash.output.data.data.attributes.names | join: ", " }}
        Tags: {{ steps.lookup_hash.output.data.data.attributes.tags | join: ", " }}
        
        {% if steps.lookup_hash.output.data.data.attributes.last_analysis_stats.malicious > 5 %}
        VERDICT: HIGH RISK — multiple engines detect this file as malicious
        {% elsif steps.lookup_hash.output.data.data.attributes.last_analysis_stats.malicious > 0 %}
        VERDICT: SUSPICIOUS — some engines flag this file
        {% else %}
        VERDICT: CLEAN — no engines flag this file
        {% endif %}
